/// 手语词汇初始数据
/// 视频命名规则：videos/signs/{category_pinyin}/{word_pinyin}.mp4
///
/// 分类拼音对照：
/// - 通用词汇: universal
/// - 日常交流: daily
/// - 情绪表达: emotion
/// - 数字时间: number_time
/// - 地点方向: location
/// - 人物称谓: people
/// - 动作行为: action
/// - 学习教育: education
/// - 医疗健康: health
/// - 餐饮饮食: food
/// - 出行交通: transport
/// - 娱乐运动: entertainment
/// - 生活服务: service

class InitialSignData {
  static List<Map<String, String>> getAllData() {
    return [
      // ========== 通用词汇  ==========
      ...universalWords,
      // ========== 日常交流 ==========
      ...dailyWords,
      // ========== 情绪表达 ==========
      ...emotionWords,
      // ========== 数字时间  ==========
      ...numberTimeWords,
      // ========== 地点方向  ==========
      ...locationWords,
      // ========== 人物称谓 ==========
      ...peopleWords,
      // ========== 动作行为  ==========
      ...actionWords,
      // ========== 学习教育 ==========
      ...educationWords,
      // ========== 医疗健康 ==========
      ...healthWords,
      // ========== 餐饮饮食  ==========
      ...foodWords,
      // ========== 出行交通  ==========
      ...transportWords,
      // ========== 娱乐运动  ==========
      ...entertainmentWords,
      // ========== 生活服务  ==========
      ...serviceWords,
    ];
  }

  // 通用词汇
  static List<Map<String, String>> universalWords = [
    {'word': '你好', 'category': '通用词汇', 'description': '右手五指并拢，手心向左，从胸前向前上方伸出，同时微微点头', 'video_path': 'videos/signs/universal/ni_hao.mp4'},
    {'word': '谢谢', 'category': '通用词汇', 'description': '右手五指并拢伸直，手心向内，从嘴边向前推出', 'video_path': 'videos/signs/universal/xie_xie.mp4'},
    {'word': '对不起', 'category': '通用词汇', 'description': '右手握拳，拳心向下，在胸前做圆形运动', 'video_path': 'videos/signs/universal/dui_bu_qi.mp4'},
    {'word': '没关系', 'category': '通用词汇', 'description': '双手手心向下，交叉摆动两次', 'video_path': 'videos/signs/universal/mei_guan_xi.mp4'},
    {'word': '再见', 'category': '通用词汇', 'description': '右手举起，手心向外，左右摆动', 'video_path': 'videos/signs/universal/zai_jian.mp4'},
    {'word': '请', 'category': '通用词汇', 'description': '右手手心向上，从右向左做邀请状', 'video_path': 'videos/signs/universal/qing.mp4'},
    {'word': '是', 'category': '通用词汇', 'description': '右手食指向上竖起，做点头状', 'video_path': 'videos/signs/universal/shi.mp4'},
    {'word': '不是', 'category': '通用词汇', 'description': '右手食指左右摆动', 'video_path': 'videos/signs/universal/bu_shi.mp4'},
    {'word': '可以', 'category': '通用词汇', 'description': '双手拇指向上竖起', 'video_path': 'videos/signs/universal/ke_yi.mp4'},
    {'word': '不可以', 'category': '通用词汇', 'description': '双手手心向前，交叉摆动', 'video_path': 'videos/signs/universal/bu_ke_yi.mp4'},
    {'word': '好', 'category': '通用词汇', 'description': '右手拇指向上竖起', 'video_path': 'videos/signs/universal/hao.mp4'},
    {'word': '不好', 'category': '通用词汇', 'description': '右手拇指向下', 'video_path': 'videos/signs/universal/bu_hao.mp4'},
    {'word': '帮助', 'category': '通用词汇', 'description': '左手手心向上，右手放在左手上方做推送状', 'video_path': 'videos/signs/universal/bang_zhu.mp4'},
    {'word': '明白', 'category': '通用词汇', 'description': '右手食指指向太阳穴，然后向外打开', 'video_path': 'videos/signs/universal/ming_bai.mp4'},
    {'word': '不明白', 'category': '通用词汇', 'description': '右手食指在太阳穴旁转圈', 'video_path': 'videos/signs/universal/bu_ming_bai.mp4'},
    {'word': '等一下', 'category': '通用词汇', 'description': '右手食指竖起，做停止状', 'video_path': 'videos/signs/universal/deng_yi_xia.mp4'},
    {'word': '慢一点', 'category': '通用词汇', 'description': '双手手心向下，缓慢向下按', 'video_path': 'videos/signs/universal/man_yi_dian.mp4'},
    {'word': '快一点', 'category': '通用词汇', 'description': '双手手心向下，快速向下挥', 'video_path': 'videos/signs/universal/kuai_yi_dian.mp4'},
    {'word': '重复', 'category': '通用词汇', 'description': '右手食指画圈', 'video_path': 'videos/signs/universal/chong_fu.mp4'},
    {'word': '没有', 'category': '通用词汇', 'description': '双手手心相对，向两边分开', 'video_path': 'videos/signs/universal/mei_you.mp4'},
    {'word': '有', 'category': '通用词汇', 'description': '双手握拳，拳心向上', 'video_path': 'videos/signs/universal/you.mp4'},
    {'word': '需要', 'category': '通用词汇', 'description': '右手向前伸，手心向上做抓取状', 'video_path': 'videos/signs/universal/xu_yao.mp4'},
    {'word': '不需要', 'category': '通用词汇', 'description': '右手手心向前推出', 'video_path': 'videos/signs/universal/bu_xu_yao.mp4'},
    {'word': '喜欢', 'category': '通用词汇', 'description': '右手放在胸前，向外拍两下', 'video_path': 'videos/signs/universal/xi_huan.mp4'},
    {'word': '不喜欢', 'category': '通用词汇', 'description': '右手在胸前推开', 'video_path': 'videos/signs/universal/bu_xi_huan.mp4'},
    {'word': '想', 'category': '通用词汇', 'description': '右手食指指向太阳穴', 'video_path': 'videos/signs/universal/xiang.mp4'},
    {'word': '不想', 'category': '通用词汇', 'description': '右手在太阳穴旁摆动', 'video_path': 'videos/signs/universal/bu_xiang.mp4'},
    {'word': '知道', 'category': '通用词汇', 'description': '右手食指点太阳穴', 'video_path': 'videos/signs/universal/zhi_dao.mp4'},
    {'word': '不知道', 'category': '通用词汇', 'description': '右手在额头前摆动', 'video_path': 'videos/signs/universal/bu_zhi_dao.mp4'},
    {'word': '同意', 'category': '通用词汇', 'description': '双手拇指竖起，向下点两次', 'video_path': 'videos/signs/universal/tong_yi.mp4'},
    {'word': '不同意', 'category': '通用词汇', 'description': '双手交叉，左右摆动', 'video_path': 'videos/signs/universal/bu_tong_yi.mp4'},
    {'word': '问题', 'category': '通用词汇', 'description': '右手食指弯曲成问号状', 'video_path': 'videos/signs/universal/wen_ti.mp4'},
    {'word': '回答', 'category': '通用词汇', 'description': '右手从嘴边向前伸出', 'video_path': 'videos/signs/universal/hui_da.mp4'},
    {'word': '开始', 'category': '通用词汇', 'description': '右手食指向前推出', 'video_path': 'videos/signs/universal/kai_shi.mp4'},
    {'word': '结束', 'category': '通用词汇', 'description': '双手手心相对，做合拢状', 'video_path': 'videos/signs/universal/jie_shu.mp4'},
    {'word': '继续', 'category': '通用词汇', 'description': '右手向前做挥动状', 'video_path': 'videos/signs/universal/ji_xu.mp4'},
    {'word': '停止', 'category': '通用词汇', 'description': '右手手心向前，做停止状', 'video_path': 'videos/signs/universal/ting_zhi.mp4'},
    {'word': '注意', 'category': '通用词汇', 'description': '双手食指指向眼睛，然后向前指', 'video_path': 'videos/signs/universal/zhu_yi.mp4'},
    {'word': '小心', 'category': '通用词汇', 'description': '右手食指在眼前摆动', 'video_path': 'videos/signs/universal/xiao_xin.mp4'},
    {'word': '危险', 'category': '通用词汇', 'description': '双手交叉在胸前快速摆动', 'video_path': 'videos/signs/universal/wei_xian.mp4'},
    {'word': '安全', 'category': '通用词汇', 'description': '双手手心向下，平稳向下按', 'video_path': 'videos/signs/universal/an_quan.mp4'},
    {'word': '重要', 'category': '通用词汇', 'description': '右手握拳，重重向下敲', 'video_path': 'videos/signs/universal/zhong_yao.mp4'},
    {'word': '容易', 'category': '通用词汇', 'description': '右手轻轻向下划', 'video_path': 'videos/signs/universal/rong_yi.mp4'},
    {'word': '困难', 'category': '通用词汇', 'description': '右手握拳，费力向上举', 'video_path': 'videos/signs/universal/kun_nan.mp4'},
    {'word': '可能', 'category': '通用词汇', 'description': '双手手心向上，上下移动', 'video_path': 'videos/signs/universal/ke_neng.mp4'},
    {'word': '不可能', 'category': '通用词汇', 'description': '双手交叉，坚决摆动', 'video_path': 'videos/signs/universal/bu_ke_neng.mp4'},
    {'word': '一定', 'category': '通用词汇', 'description': '右手握拳，用力向下点', 'video_path': 'videos/signs/universal/yi_ding.mp4'},
    {'word': '也许', 'category': '通用词汇', 'description': '右手手心向上，轻轻摆动', 'video_path': 'videos/signs/universal/ye_xu.mp4'},
    {'word': '当然', 'category': '通用词汇', 'description': '双手拇指向上，用力点两次', 'video_path': 'videos/signs/universal/dang_ran.mp4'},
    {'word': '差不多', 'category': '通用词汇', 'description': '双手手心相对，做接近状', 'video_path': 'videos/signs/universal/cha_bu_duo.mp4'},
    {'word': '正确', 'category': '通用词汇', 'description': '右手食指指向太阳穴，然后向前点出', 'video_path': 'videos/signs/universal/zheng_que.mp4'},
    {'word': '错误', 'category': '通用词汇', 'description': '右手食指左右摆动，表示不对', 'video_path': 'videos/signs/universal/cuo_wu.mp4'},
    {'word': '完成', 'category': '通用词汇', 'description': '双手手心向下，向下按压', 'video_path': 'videos/signs/universal/wan_cheng.mp4'},
    {'word': '成功', 'category': '通用词汇', 'description': '双手握拳向上举起', 'video_path': 'videos/signs/universal/cheng_gong.mp4'},
    {'word': '失败', 'category': '通用词汇', 'description': '双手手心向下，向下摊开', 'video_path': 'videos/signs/universal/shi_bai.mp4'},
    {'word': '努力', 'category': '通用词汇', 'description': '双手握拳，上下用力', 'video_path': 'videos/signs/universal/nu_li.mp4'},
    {'word': '认真', 'category': '通用词汇', 'description': '右手食指点太阳穴，表示用心', 'video_path': 'videos/signs/universal/ren_zhen.mp4'},
    {'word': '随便', 'category': '通用词汇', 'description': '右手手心向上，随意摆动', 'video_path': 'videos/signs/universal/sui_bian.mp4'},
    {'word': '最好', 'category': '通用词汇', 'description': '右手拇指竖起，向上举', 'video_path': 'videos/signs/universal/zui_hao.mp4'},
    {'word': '最差', 'category': '通用词汇', 'description': '右手拇指向下，向下指', 'video_path': 'videos/signs/universal/zui_cha.mp4'},
    {'word': '第一', 'category': '通用词汇', 'description': '右手食指竖起表示数字1', 'video_path': 'videos/signs/universal/di_yi.mp4'},
    {'word': '最后', 'category': '通用词汇', 'description': '右手向身后指', 'video_path': 'videos/signs/universal/zui_hou.mp4'},
    {'word': '前面', 'category': '通用词汇', 'description': '右手向前指', 'video_path': 'videos/signs/universal/qian_mian.mp4'},
    {'word': '后面', 'category': '通用词汇', 'description': '右手向后指', 'video_path': 'videos/signs/universal/hou_mian.mp4'},
    {'word': '左边', 'category': '通用词汇', 'description': '右手向左指', 'video_path': 'videos/signs/universal/zuo_bian.mp4'},
    {'word': '右边', 'category': '通用词汇', 'description': '右手向右指', 'video_path': 'videos/signs/universal/you_bian.mp4'},
    {'word': '上面', 'category': '通用词汇', 'description': '右手向上指', 'video_path': 'videos/signs/universal/shang_mian.mp4'},
    {'word': '下面', 'category': '通用词汇', 'description': '右手向下指', 'video_path': 'videos/signs/universal/xia_mian.mp4'},
    {'word': '里面', 'category': '通用词汇', 'description': '右手做放入状', 'video_path': 'videos/signs/universal/li_mian.mp4'},
    {'word': '外面', 'category': '通用词汇', 'description': '右手做拿出状', 'video_path': 'videos/signs/universal/wai_mian.mp4'},
    {'word': '中间', 'category': '通用词汇', 'description': '右手在两手之间指', 'video_path': 'videos/signs/universal/zhong_jian.mp4'},
    {'word': '旁边', 'category': '通用词汇', 'description': '右手向侧面指', 'video_path': 'videos/signs/universal/pang_bian.mp4'},
    {'word': '附近', 'category': '通用词汇', 'description': '右手在周围画圈', 'video_path': 'videos/signs/universal/fu_jin.mp4'},
    {'word': '远处', 'category': '通用词汇', 'description': '右手向远方指', 'video_path': 'videos/signs/universal/yuan_chu.mp4'},
    {'word': '这里', 'category': '通用词汇', 'description': '右手食指向下指自己位置', 'video_path': 'videos/signs/universal/zhe_li.mp4'},
    {'word': '那里', 'category': '通用词汇', 'description': '右手向前方指', 'video_path': 'videos/signs/universal/na_li.mp4'},
    {'word': '这个', 'category': '通用词汇', 'description': '右手食指向下指', 'video_path': 'videos/signs/universal/zhe_ge.mp4'},
    {'word': '那个', 'category': '通用词汇', 'description': '右手食指向远处指', 'video_path': 'videos/signs/universal/na_ge.mp4'},
    {'word': '这些', 'category': '通用词汇', 'description': '右手张开，向自己方向挥', 'video_path': 'videos/signs/universal/zhe_xie.mp4'},
    {'word': '那些', 'category': '通用词汇', 'description': '右手张开，向远处挥', 'video_path': 'videos/signs/universal/na_xie.mp4'},
    {'word': '全部', 'category': '通用词汇', 'description': '双手张开，从两边向中间聚拢', 'video_path': 'videos/signs/universal/quan_bu.mp4'},
    {'word': '部分', 'category': '通用词汇', 'description': '右手食指指向一部分', 'video_path': 'videos/signs/universal/bu_fen.mp4'},
    {'word': '每个', 'category': '通用词汇', 'description': '右手食指依次指点', 'video_path': 'videos/signs/universal/mei_ge.mp4'},
    {'word': '几个', 'category': '通用词汇', 'description': '右手做计数手势', 'video_path': 'videos/signs/universal/ji_ge.mp4'},
    {'word': '一些', 'category': '通用词汇', 'description': '右手张开，表示少量', 'video_path': 'videos/signs/universal/yi_xie.mp4'},
    {'word': '很多', 'category': '通用词汇', 'description': '双手张开，表示大量', 'video_path': 'videos/signs/universal/hen_duo.mp4'},
    {'word': '一点', 'category': '通用词汇', 'description': '右手拇指和食指捏在一起', 'video_path': 'videos/signs/universal/yi_dian.mp4'},
    {'word': '所有', 'category': '通用词汇', 'description': '双手张开，然后合拢', 'video_path': 'videos/signs/universal/suo_you.mp4'},
    {'word': '唯一', 'category': '通用词汇', 'description': '右手食指竖起', 'video_path': 'videos/signs/universal/wei_yi.mp4'},
    {'word': '相同', 'category': '通用词汇', 'description': '双手食指并排', 'video_path': 'videos/signs/universal/xiang_tong.mp4'},
    {'word': '不同', 'category': '通用词汇', 'description': '双手食指分开', 'video_path': 'videos/signs/universal/bu_tong.mp4'},
    {'word': '一样', 'category': '通用词汇', 'description': '双手手心相对，高度相同', 'video_path': 'videos/signs/universal/yi_yang.mp4'},
    {'word': '不一样', 'category': '通用词汇', 'description': '双手一高一低', 'video_path': 'videos/signs/universal/bu_yi_yang.mp4'},
    {'word': '相似', 'category': '通用词汇', 'description': '双手手心相对，做比较状', 'video_path': 'videos/signs/universal/xiang_si.mp4'},
    {'word': '相反', 'category': '通用词汇', 'description': '双手向相反方向移动', 'video_path': 'videos/signs/universal/xiang_fan.mp4'},
    {'word': '互相', 'category': '通用词汇', 'description': '双手食指交替指向对方', 'video_path': 'videos/signs/universal/hu_xiang.mp4'},
    {'word': '彼此', 'category': '通用词汇', 'description': '双手交替指自己和对方', 'video_path': 'videos/signs/universal/bi_ci.mp4'},
    {'word': '自己', 'category': '通用词汇', 'description': '右手食指向下指自己', 'video_path': 'videos/signs/universal/zi_ji.mp4'},
    {'word': '别人', 'category': '通用词汇', 'description': '右手食指向远处指', 'video_path': 'videos/signs/universal/bie_ren.mp4'},
    {'word': '大家', 'category': '通用词汇', 'description': '双手张开，表示所有人', 'video_path': 'videos/signs/universal/da_jia.mp4'},
    {'word': '一起', 'category': '通用词汇', 'description': '双手合拢', 'video_path': 'videos/signs/universal/yi_qi.mp4'},
    {'word': '单独', 'category': '通用词汇', 'description': '右手食指单独竖起', 'video_path': 'videos/signs/universal/dan_du.mp4'},
    {'word': '共同', 'category': '通用词汇', 'description': '双手合在一起', 'video_path': 'videos/signs/universal/gong_tong.mp4'},
    {'word': '合作', 'category': '通用词汇', 'description': '双手握在一起', 'video_path': 'videos/signs/universal/he_zuo.mp4'},
    {'word': '竞争', 'category': '通用词汇', 'description': '双手食指相对', 'video_path': 'videos/signs/universal/jing_zheng.mp4'},
    {'word': '比较', 'category': '通用词汇', 'description': '双手手心相对，上下移动', 'video_path': 'videos/signs/universal/bi_jiao.mp4'},
    {'word': '选择', 'category': '通用词汇', 'description': '右手食指在空中指点', 'video_path': 'videos/signs/universal/xuan_ze.mp4'},
    {'word': '决定', 'category': '通用词汇', 'description': '右手握拳向下敲', 'video_path': 'videos/signs/universal/jue_ding.mp4'},
    {'word': '计划', 'category': '通用词汇', 'description': '右手在左手掌上比划', 'video_path': 'videos/signs/universal/ji_hua.mp4'},
    {'word': '目标', 'category': '通用词汇', 'description': '右手食指指向远方', 'video_path': 'videos/signs/universal/mu_biao.mp4'},
    {'word': '希望', 'category': '通用词汇', 'description': '双手放在胸前，向上抬起', 'video_path': 'videos/signs/universal/xi_wang.mp4'},
    {'word': '梦想', 'category': '通用词汇', 'description': '右手食指在太阳穴转圈', 'video_path': 'videos/signs/universal/meng_xiang.mp4'},
    {'word': '现实', 'category': '通用词汇', 'description': '右手向下指地面', 'video_path': 'videos/signs/universal/xian_shi.mp4'},
    {'word': '理想', 'category': '通用词汇', 'description': '右手食指向上指', 'video_path': 'videos/signs/universal/li_xiang.mp4'},
    {'word': '自由', 'category': '通用词汇', 'description': '双手向上张开', 'video_path': 'videos/signs/universal/zi_you.mp4'},
    {'word': '平等', 'category': '通用词汇', 'description': '双手手心向下，保持水平', 'video_path': 'videos/signs/universal/ping_deng.mp4'},
    {'word': '公正', 'category': '通用词汇', 'description': '双手做天平状', 'video_path': 'videos/signs/universal/gong_zheng.mp4'},
    {'word': '公平', 'category': '通用词汇', 'description': '双手手心向上，高度相同', 'video_path': 'videos/signs/universal/gong_ping.mp4'},
    {'word': '正义', 'category': '通用词汇', 'description': '右手握拳在胸前', 'video_path': 'videos/signs/universal/zheng_yi.mp4'},
    {'word': '责任', 'category': '通用词汇', 'description': '右手拍肩膀', 'video_path': 'videos/signs/universal/ze_ren.mp4'},
    {'word': '义务', 'category': '通用词汇', 'description': '右手做承诺状', 'video_path': 'videos/signs/universal/yi_wu.mp4'},
    {'word': '权利', 'category': '通用词汇', 'description': '右手握拳举起', 'video_path': 'videos/signs/universal/quan_li.mp4'},
    {'word': '义务', 'category': '通用词汇', 'description': '右手做承诺状', 'video_path': 'videos/signs/universal/yi_wu2.mp4'},
    {'word': '社会', 'category': '通用词汇', 'description': '双手张开，表示众人', 'video_path': 'videos/signs/universal/she_hui.mp4'},
    {'word': '国家', 'category': '通用词汇', 'description': '右手在胸前画圈', 'video_path': 'videos/signs/universal/guo_jia.mp4'},
    {'word': '民族', 'category': '通用词汇', 'description': '右手在胸口画心形', 'video_path': 'videos/signs/universal/min_zu.mp4'},
    {'word': '世界', 'category': '通用词汇', 'description': '双手画大圈', 'video_path': 'videos/signs/universal/shi_jie.mp4'},
    {'word': '地球', 'category': '通用词汇', 'description': '双手做球状', 'video_path': 'videos/signs/universal/di_qiu.mp4'},
    {'word': '自然', 'category': '通用词汇', 'description': '双手做树生长状', 'video_path': 'videos/signs/universal/zi_ran.mp4'},
    {'word': '环境', 'category': '通用词汇', 'description': '双手在周围画圈', 'video_path': 'videos/signs/universal/huan_jing.mp4'},
    {'word': '保护', 'category': '通用词汇', 'description': '双手做环抱状', 'video_path': 'videos/signs/universal/bao_hu.mp4'},
    {'word': '破坏', 'category': '通用词汇', 'description': '双手做撕碎状', 'video_path': 'videos/signs/universal/po_huai.mp4'},
    {'word': '建设', 'category': '通用词汇', 'description': '双手做搭建状', 'video_path': 'videos/signs/universal/jian_she.mp4'},
    {'word': '发展', 'category': '通用词汇', 'description': '双手向上展开', 'video_path': 'videos/signs/universal/fa_zhan.mp4'},
    {'word': '进步', 'category': '通用词汇', 'description': '右手向上移动', 'video_path': 'videos/signs/universal/jin_bu.mp4'},
    {'word': '落后', 'category': '通用词汇', 'description': '右手向下移动', 'video_path': 'videos/signs/universal/luo_hou.mp4'},
    {'word': '变化', 'category': '通用词汇', 'description': '右手做波浪状', 'video_path': 'videos/signs/universal/bian_hua.mp4'},
    {'word': '稳定', 'category': '通用词汇', 'description': '双手手心向下，保持平稳', 'video_path': 'videos/signs/universal/wen_ding.mp4'},
    {'word': '混乱', 'category': '通用词汇', 'description': '双手乱挥', 'video_path': 'videos/signs/universal/hun_luan.mp4'},
    {'word': '秩序', 'category': '通用词汇', 'description': '右手依次指点', 'video_path': 'videos/signs/universal/zhi_xu.mp4'},
    {'word': '规则', 'category': '通用词汇', 'description': '右手画方框', 'video_path': 'videos/signs/universal/gui_ze.mp4'},
    {'word': '法律', 'category': '通用词汇', 'description': '右手做敲法槌状', 'video_path': 'videos/signs/universal/fa_lv.mp4'},
    {'word': '道德', 'category': '通用词汇', 'description': '右手放在心口', 'video_path': 'videos/signs/universal/dao_de.mp4'},
    {'word': '良心', 'category': '通用词汇', 'description': '右手在胸口画心形', 'video_path': 'videos/signs/universal/liang_xin.mp4'},
    {'word': '诚实', 'category': '通用词汇', 'description': '右手放在胸口', 'video_path': 'videos/signs/universal/cheng_shi.mp4'},
    {'word': '欺骗', 'category': '通用词汇', 'description': '右手在眼前遮挡', 'video_path': 'videos/signs/universal/qi_pian.mp4'},
    {'word': '信任', 'category': '通用词汇', 'description': '双手握在一起', 'video_path': 'videos/signs/universal/xin_ren.mp4'},
    {'word': '怀疑', 'category': '通用词汇', 'description': '右手食指在太阳穴转圈', 'video_path': 'videos/signs/universal/huai_yi.mp4'},
    {'word': '相信', 'category': '通用词汇', 'description': '右手放在心口', 'video_path': 'videos/signs/universal/xiang_xin.mp4'},
    {'word': '不信', 'category': '通用词汇', 'description': '右手在胸前摆动', 'video_path': 'videos/signs/universal/bu_xin.mp4'},
    {'word': '尊重', 'category': '通用词汇', 'description': '右手放在胸前鞠躬', 'video_path': 'videos/signs/universal/zun_zhong.mp4'},
    {'word': '鄙视', 'category': '通用词汇', 'description': '右手向下挥', 'video_path': 'videos/signs/universal/bi_shi.mp4'},
    {'word': '羡慕', 'category': '通用词汇', 'description': '双手放在下巴处', 'video_path': 'videos/signs/universal/xian_mu.mp4'},
    {'word': '嫉妒', 'category': '通用词汇', 'description': '右手在眼前偷看', 'video_path': 'videos/signs/universal/ji_du.mp4'},
    {'word': '宽容', 'category': '通用词汇', 'description': '双手张开', 'video_path': 'videos/signs/universal/kuan_rong.mp4'},
    {'word': '狭隘', 'category': '通用词汇', 'description': '双手靠近', 'video_path': 'videos/signs/universal/xia_ai.mp4'},
    {'word': '大方', 'category': '通用词汇', 'description': '双手向外张开', 'video_path': 'videos/signs/universal/da_fang.mp4'},
    {'word': '小气', 'category': '通用词汇', 'description': '双手握紧', 'video_path': 'videos/signs/universal/xiao_qi.mp4'},
    {'word': '勇敢', 'category': '通用词汇', 'description': '右手握拳在胸前', 'video_path': 'videos/signs/universal/yong_gan.mp4'},
    {'word': '胆小', 'category': '通用词汇', 'description': '双手抱肩发抖', 'video_path': 'videos/signs/universal/dan_xiao.mp4'},
    {'word': '坚强', 'category': '通用词汇', 'description': '右手握拳用力', 'video_path': 'videos/signs/universal/jian_qiang.mp4'},
    {'word': '软弱', 'category': '通用词汇', 'description': '右手无力下垂', 'video_path': 'videos/signs/universal/ruan_ruo.mp4'},
    {'word': '积极', 'category': '通用词汇', 'description': '双手向上举', 'video_path': 'videos/signs/universal/ji_ji.mp4'},
    {'word': '消极', 'category': '通用词汇', 'description': '双手向下垂', 'video_path': 'videos/signs/universal/xiao_ji.mp4'},
    {'word': '乐观', 'category': '通用词汇', 'description': '右手在嘴角向上划', 'video_path': 'videos/signs/universal/le_guan.mp4'},
    {'word': '悲观', 'category': '通用词汇', 'description': '右手在嘴角向下划', 'video_path': 'videos/signs/universal/bei_guan.mp4'},
    {'word': '开朗', 'category': '通用词汇', 'description': '双手从胸前向外打开', 'video_path': 'videos/signs/universal/kai_lang.mp4'},
    {'word': '内向', 'category': '通用词汇', 'description': '双手向胸前收缩', 'video_path': 'videos/signs/universal/nei_xiang.mp4'},
    {'word': '外向', 'category': '通用词汇', 'description': '双手向外张开', 'video_path': 'videos/signs/universal/wai_xiang.mp4'},
    {'word': '热情', 'category': '通用词汇', 'description': '双手在胸前燃烧状', 'video_path': 'videos/signs/universal/re_qing.mp4'},
    {'word': '冷淡', 'category': '通用词汇', 'description': '双手交叉抱胸', 'video_path': 'videos/signs/universal/leng_dan.mp4'},
    {'word': '友好', 'category': '通用词汇', 'description': '双手握在一起', 'video_path': 'videos/signs/universal/you_hao.mp4'},
    {'word': '敌对', 'category': '通用词汇', 'description': '双手食指相对', 'video_path': 'videos/signs/universal/di_dui.mp4'},
    {'word': '亲密', 'category': '通用词汇', 'description': '双手靠近', 'video_path': 'videos/signs/universal/qin_mi.mp4'},
    {'word': '疏远', 'category': '通用词汇', 'description': '双手分开', 'video_path': 'videos/signs/universal/shu_yuan.mp4'},
    {'word': '爱情', 'category': '通用词汇', 'description': '双手在胸前比心', 'video_path': 'videos/signs/universal/ai_qing.mp4'},
    {'word': '友情', 'category': '通用词汇', 'description': '双手握在一起', 'video_path': 'videos/signs/universal/you_qing.mp4'},
    {'word': '亲情', 'category': '通用词汇', 'description': '双手抱在一起', 'video_path': 'videos/signs/universal/qin_qing.mp4'},
    {'word': '仇恨', 'category': '通用词汇', 'description': '双手握拳相对', 'video_path': 'videos/signs/universal/chou_hen.mp4'},
    {'word': '原谅', 'category': '通用词汇', 'description': '双手从胸前向外推', 'video_path': 'videos/signs/universal/yuan_liang.mp4'},
    {'word': '报复', 'category': '通用词汇', 'description': '右手握拳敲击', 'video_path': 'videos/signs/universal/bao_fu.mp4'},
    {'word': '和平', 'category': '通用词汇', 'description': '双手做鸽子飞翔状', 'video_path': 'videos/signs/universal/he_ping.mp4'},
    {'word': '战争', 'category': '通用词汇', 'description': '双手做枪战状', 'video_path': 'videos/signs/universal/zhan_zheng.mp4'},
    {'word': '生命', 'category': '通用词汇', 'description': '右手做心跳状', 'video_path': 'videos/signs/universal/sheng_ming.mp4'},
    {'word': '死亡', 'category': '通用词汇', 'description': '右手在脖子前划过', 'video_path': 'videos/signs/universal/si_wang.mp4'},
    {'word': '健康', 'category': '通用词汇', 'description': '右手拍胸口', 'video_path': 'videos/signs/universal/jian_kang.mp4'},
    {'word': '疾病', 'category': '通用词汇', 'description': '右手捂胸口咳嗽', 'video_path': 'videos/signs/universal/ji_bing.mp4'},
    {'word': '年轻', 'category': '通用词汇', 'description': '右手在脸旁向上划', 'video_path': 'videos/signs/universal/nian_qing.mp4'},
    {'word': '年老', 'category': '通用词汇', 'description': '右手在脸旁向下划', 'video_path': 'videos/signs/universal/nian_lao.mp4'},
    {'word': '美丽', 'category': '通用词汇', 'description': '右手在脸前划圈', 'video_path': 'videos/signs/universal/mei_li.mp4'},
    {'word': '丑陋', 'category': '通用词汇', 'description': '右手在脸前摆动', 'video_path': 'videos/signs/universal/chou_lou.mp4'},
    {'word': '高大', 'category': '通用词汇', 'description': '右手向上举', 'video_path': 'videos/signs/universal/gao_da.mp4'},
    {'word': '矮小', 'category': '通用词汇', 'description': '右手向下压', 'video_path': 'videos/signs/universal/ai_xiao.mp4'},
    {'word': '强壮', 'category': '通用词汇', 'description': '右手展示肌肉', 'video_path': 'videos/signs/universal/qiang_zhuang.mp4'},
    {'word': '瘦弱', 'category': '通用词汇', 'description': '右手展示细胳膊', 'video_path': 'videos/signs/universal/shou_ruo.mp4'},
    {'word': '富裕', 'category': '通用词汇', 'description': '右手做数钱状', 'video_path': 'videos/signs/universal/fu_yu.mp4'},
    {'word': '贫穷', 'category': '通用词汇', 'description': '右手做乞讨状', 'video_path': 'videos/signs/universal/pin_qiong.mp4'},
    {'word': '幸福', 'category': '通用词汇', 'description': '右手拍胸口微笑', 'video_path': 'videos/signs/universal/xing_fu2.mp4'},
    {'word': '痛苦', 'category': '通用词汇', 'description': '右手捂胸口皱眉', 'video_path': 'videos/signs/universal/tong_ku2.mp4'},
    {'word': '快乐', 'category': '通用词汇', 'description': '双手向上挥动', 'video_path': 'videos/signs/universal/kuai_le2.mp4'},
    {'word': '悲伤', 'category': '通用词汇', 'description': '双手从眼睛向下划', 'video_path': 'videos/signs/universal/bei_shang.mp4'},
    {'word': '忙碌', 'category': '通用词汇', 'description': '双手快速交替', 'video_path': 'videos/signs/universal/mang_lu.mp4'},
    {'word': '悠闲', 'category': '通用词汇', 'description': '双手慢慢摆动', 'video_path': 'videos/signs/universal/you_xian.mp4'},
    {'word': '紧张', 'category': '通用词汇', 'description': '双手握紧', 'video_path': 'videos/signs/universal/jin_zhang2.mp4'},
    {'word': '放松', 'category': '通用词汇', 'description': '双手张开', 'video_path': 'videos/signs/universal/fang_song2.mp4'},
    {'word': '简单', 'category': '通用词汇', 'description': '右手轻轻一挥', 'video_path': 'videos/signs/universal/jian_dan.mp4'},
    {'word': '复杂', 'category': '通用词汇', 'description': '双手交织', 'video_path': 'videos/signs/universal/fu_za.mp4'},
    {'word': '清楚', 'category': '通用词汇', 'description': '右手在眼前打开', 'video_path': 'videos/signs/universal/qing_chu.mp4'},
    {'word': '模糊', 'category': '通用词汇', 'description': '右手在眼前晃动', 'video_path': 'videos/signs/universal/mo_hu.mp4'},
    {'word': '明亮', 'category': '通用词汇', 'description': '双手做发光状', 'video_path': 'videos/signs/universal/ming_liang.mp4'},
    {'word': '黑暗', 'category': '通用词汇', 'description': '双手在眼前遮挡', 'video_path': 'videos/signs/universal/hei_an.mp4'},
    {'word': '安静', 'category': '通用词汇', 'description': '右手食指竖在嘴前', 'video_path': 'videos/signs/universal/an_jing.mp4'},
    {'word': '吵闹', 'category': '通用词汇', 'description': '双手在耳边摆动', 'video_path': 'videos/signs/universal/chao_nao.mp4'},
    {'word': '干净', 'category': '通用词汇', 'description': '右手做擦拭状', 'video_path': 'videos/signs/universal/gan_jing.mp4'},
    {'word': '肮脏', 'category': '通用词汇', 'description': '右手做甩脏东西状', 'video_path': 'videos/signs/universal/ang_zang.mp4'},
    {'word': '整齐', 'category': '通用词汇', 'description': '右手依次排列', 'video_path': 'videos/signs/universal/zheng_qi.mp4'},
    {'word': '杂乱', 'category': '通用词汇', 'description': '双手乱挥', 'video_path': 'videos/signs/universal/za_luan.mp4'},
    {'word': '新鲜', 'category': '通用词汇', 'description': '右手在鼻子前扇风', 'video_path': 'videos/signs/universal/xin_xian.mp4'},
    {'word': '陈旧', 'category': '通用词汇', 'description': '右手做拍灰尘状', 'video_path': 'videos/signs/universal/chen_jiu.mp4'},
    {'word': '现代', 'category': '通用词汇', 'description': '右手做按手机状', 'video_path': 'videos/signs/universal/xian_dai.mp4'},
    {'word': '传统', 'category': '通用词汇', 'description': '右手做写毛笔字状', 'video_path': 'videos/signs/universal/chuan_tong.mp4'},
    {'word': '流行', 'category': '通用词汇', 'description': '右手做波浪状移动', 'video_path': 'videos/signs/universal/liu_xing.mp4'},
    {'word': '过时', 'category': '通用词汇', 'description': '右手向后指', 'video_path': 'videos/signs/universal/guo_shi.mp4'},
    {'word': '时尚', 'category': '通用词汇', 'description': '右手在身前划圈', 'video_path': 'videos/signs/universal/shi_shang.mp4'},
    {'word': '朴素', 'category': '通用词汇', 'description': '右手做简单手势', 'video_path': 'videos/signs/universal/pu_su.mp4'},
    {'word': '奢侈', 'category': '通用词汇', 'description': '右手做展示珠宝状', 'video_path': 'videos/signs/universal/she_chi.mp4'},
    {'word': '节约', 'category': '通用词汇', 'description': '双手握紧', 'video_path': 'videos/signs/universal/jie_yue.mp4'},
    {'word': '浪费', 'category': '通用词汇', 'description': '右手做扔掉状', 'video_path': 'videos/signs/universal/lang_fei.mp4'},
    {'word': '环保', 'category': '通用词汇', 'description': '双手做树状', 'video_path': 'videos/signs/universal/huan_bao.mp4'},
    {'word': '污染', 'category': '通用词汇', 'description': '右手做排放状', 'video_path': 'videos/signs/universal/wu_ran.mp4'},
    {'word': '温暖', 'category': '通用词汇', 'description': '双手抱肩', 'video_path': 'videos/signs/universal/wen_nuan.mp4'},
    {'word': '寒冷', 'category': '通用词汇', 'description': '双手抱肩发抖', 'video_path': 'videos/signs/universal/han_leng.mp4'},
    {'word': '炎热', 'category': '通用词汇', 'description': '右手在额头擦汗', 'video_path': 'videos/signs/universal/yan_re.mp4'},
    {'word': '凉爽', 'category': '通用词汇', 'description': '右手在脸前扇风', 'video_path': 'videos/signs/universal/liang_shuang.mp4'},
    {'word': '干燥', 'category': '通用词汇', 'description': '右手做裂开状', 'video_path': 'videos/signs/universal/gan_zao.mp4'},
    {'word': '潮湿', 'category': '通用词汇', 'description': '右手做滴水状', 'video_path': 'videos/signs/universal/chaoshi.mp4'},
    {'word': '坚硬', 'category': '通用词汇', 'description': '右手敲击左手', 'video_path': 'videos/signs/universal/jian_ying.mp4'},
    {'word': '柔软', 'category': '通用词汇', 'description': '右手做抚摸状', 'video_path': 'videos/signs/universal/rou_ruan.mp4'},
    {'word': '光滑', 'category': '通用词汇', 'description': '右手做滑动状', 'video_path': 'videos/signs/universal/guang_hua.mp4'},
    {'word': '粗糙', 'category': '通用词汇', 'description': '右手做摩擦状', 'video_path': 'videos/signs/universal/cu_cao.mp4'},
    {'word': '沉重', 'category': '通用词汇', 'description': '双手向下压', 'video_path': 'videos/signs/universal/chen_zhong.mp4'},
    {'word': '轻便', 'category': '通用词汇', 'description': '右手轻轻托起', 'video_path': 'videos/signs/universal/qing_bian.mp4'},
    {'word': '快速', 'category': '通用词汇', 'description': '右手快速向前', 'video_path': 'videos/signs/universal/kuai_su.mp4'},
    {'word': '缓慢', 'category': '通用词汇', 'description': '右手慢慢向前', 'video_path': 'videos/signs/universal/huan_man.mp4'},
    {'word': '紧急', 'category': '通用词汇', 'description': '双手快速挥动', 'video_path': 'videos/signs/universal/jin_ji.mp4'},
    {'word': '平常', 'category': '通用词汇', 'description': '右手平缓移动', 'video_path': 'videos/signs/universal/ping_chang.mp4'},
    {'word': '特殊', 'category': '通用词汇', 'description': '右手竖起拇指', 'video_path': 'videos/signs/universal/te_shu.mp4'},
    {'word': '一般', 'category': '通用词汇', 'description': '右手平缓摆动', 'video_path': 'videos/signs/universal/yi_ban.mp4'},
    {'word': '优秀', 'category': '通用词汇', 'description': '右手竖起拇指', 'video_path': 'videos/signs/universal/you_xiu2.mp4'},
    {'word': '普通', 'category': '通用词汇', 'description': '右手平摊', 'video_path': 'videos/signs/universal/pu_tong.mp4'},
    {'word': '卓越', 'category': '通用词汇', 'description': '右手高高竖起拇指', 'video_path': 'videos/signs/universal/zhui_yue.mp4'},
    {'word': '平凡', 'category': '通用词汇', 'description': '右手平缓移动', 'video_path': 'videos/signs/universal/ping_fan.mp4'},
    {'word': '伟大', 'category': '通用词汇', 'description': '右手向上高举', 'video_path': 'videos/signs/universal/wei_da.mp4'},
    {'word': '渺小', 'category': '通用词汇', 'description': '右手拇指食指捏在一起', 'video_path': 'videos/signs/universal/miao_xiao.mp4'},
    {'word': '重要', 'category': '通用词汇', 'description': '右手握拳敲击', 'video_path': 'videos/signs/universal/zhong_yao2.mp4'},
    {'word': '次要', 'category': '通用词汇', 'description': '右手小指竖起', 'video_path': 'videos/signs/universal/ci_yao.mp4'},
    {'word': '主要', 'category': '通用词汇', 'description': '右手拇指竖起', 'video_path': 'videos/signs/universal/zhu_yao.mp4'},
    {'word': '必要', 'category': '通用词汇', 'description': '右手食指用力点', 'video_path': 'videos/signs/universal/bi_yao.mp4'},
    {'word': '多余', 'category': '通用词汇', 'description': '右手做扔掉状', 'video_path': 'videos/signs/universal/duo_yu.mp4'},
    {'word': '足够', 'category': '通用词汇', 'description': '右手在胸前画圈', 'video_path': 'videos/signs/universal/zu_gou.mp4'},
    {'word': '缺乏', 'category': '通用词汇', 'description': '双手向外摊开', 'video_path': 'videos/signs/universal/que_fa.mp4'},
    {'word': '丰富', 'category': '通用词汇', 'description': '双手张开', 'video_path': 'videos/signs/universal/feng_fu.mp4'},
    {'word': '贫乏', 'category': '通用词汇', 'description': '双手握紧', 'video_path': 'videos/signs/universal/pin_fa.mp4'},
    {'word': '充足', 'category': '通用词汇', 'description': '右手在胸前画圈', 'video_path': 'videos/signs/universal/chong_zu.mp4'},
    {'word': '不足', 'category': '通用词汇', 'description': '右手向下压', 'video_path': 'videos/signs/universal/bu_zu.mp4'},
    {'word': '完整', 'category': '通用词汇', 'description': '双手画圈', 'video_path': 'videos/signs/universal/wan_zheng.mp4'},
    {'word': '残缺', 'category': '通用词汇', 'description': '右手展示缺口', 'video_path': 'videos/signs/universal/can_que.mp4'},
    {'word': '完美', 'category': '通用词汇', 'description': '右手画圈', 'video_path': 'videos/signs/universal/wan_mei.mp4'},
    {'word': '缺陷', 'category': '通用词汇', 'description': '右手指出缺点', 'video_path': 'videos/signs/universal/que_xian.mp4'},
    {'word': '优势', 'category': '通用词汇', 'description': '右手拇指竖起', 'video_path': 'videos/signs/universal/you_shi.mp4'},
    {'word': '劣势', 'category': '通用词汇', 'description': '右手小指竖起', 'video_path': 'videos/signs/universal/lie_shi.mp4'},
    {'word': '长处', 'category': '通用词汇', 'description': '右手展示优点', 'video_path': 'videos/signs/universal/chang_chu.mp4'},
    {'word': '短处', 'category': '通用词汇', 'description': '右手指出缺点', 'video_path': 'videos/signs/universal/duan_chu.mp4'},
    {'word': '优点', 'category': '通用词汇', 'description': '右手拇指竖起', 'video_path': 'videos/signs/universal/you_dian.mp4'},
    {'word': '缺点', 'category': '通用词汇', 'description': '右手食指指出问题', 'video_path': 'videos/signs/universal/que_dian.mp4'},
    {'word': '好处', 'category': '通用词汇', 'description': '右手做接收状', 'video_path': 'videos/signs/universal/hao_chu.mp4'},
    {'word': '坏处', 'category': '通用词汇', 'description': '右手做推拒状', 'video_path': 'videos/signs/universal/huai_chu.mp4'},
    {'word': '利益', 'category': '通用词汇', 'description': '右手做数钱状', 'video_path': 'videos/signs/universal/li_yi.mp4'},
    {'word': '损失', 'category': '通用词汇', 'description': '双手向外摊开', 'video_path': 'videos/signs/universal/sun_shi.mp4'},
    {'word': '收获', 'category': '通用词汇', 'description': '右手做收集状', 'video_path': 'videos/signs/universal/shou_huo.mp4'},
    {'word': '付出', 'category': '通用词汇', 'description': '右手做给予状', 'video_path': 'videos/signs/universal/fu_chu.mp4'},
    {'word': '得到', 'category': '通用词汇', 'description': '右手做接收状', 'video_path': 'videos/signs/universal/de_dao.mp4'},
    {'word': '失去', 'category': '通用词汇', 'description': '双手向外摊开', 'video_path': 'videos/signs/universal/shi_qu.mp4'},
    {'word': '拥有', 'category': '通用词汇', 'description': '双手握拳', 'video_path': 'videos/signs/universal/yong_you.mp4'},
    {'word': '缺少', 'category': '通用词汇', 'description': '双手向外摊开', 'video_path': 'videos/signs/universal/que_shao.mp4'},
    {'word': '增加', 'category': '通用词汇', 'description': '右手向上移动', 'video_path': 'videos/signs/universal/zeng_jia.mp4'},
    {'word': '减少', 'category': '通用词汇', 'description': '右手向下移动', 'video_path': 'videos/signs/universal/jian_shao.mp4'},
    {'word': '提高', 'category': '通用词汇', 'description': '右手向上移动', 'video_path': 'videos/signs/universal/ti_gao.mp4'},
    {'word': '降低', 'category': '通用词汇', 'description': '右手向下移动', 'video_path': 'videos/signs/universal/jiang_di.mp4'},
    {'word': '上升', 'category': '通用词汇', 'description': '右手向上移动', 'video_path': 'videos/signs/universal/shang_sheng.mp4'},
    {'word': '下降', 'category': '通用词汇', 'description': '右手向下移动', 'video_path': 'videos/signs/universal/xia_jiang.mp4'},
    {'word': '前进', 'category': '通用词汇', 'description': '右手向前移动', 'video_path': 'videos/signs/universal/qian_jin.mp4'},
    {'word': '后退', 'category': '通用词汇', 'description': '右手向后移动', 'video_path': 'videos/signs/universal/hou_tui.mp4'},
    {'word': '到达', 'category': '通用词汇', 'description': '右手点向前方', 'video_path': 'videos/signs/universal/dao_da.mp4'},
    {'word': '离开', 'category': '通用词汇', 'description': '右手向后移动', 'video_path': 'videos/signs/universal/li_kai.mp4'},
    {'word': '进入', 'category': '通用词汇', 'description': '右手做进入状', 'video_path': 'videos/signs/universal/jin_ru.mp4'},
    {'word': '退出', 'category': '通用词汇', 'description': '右手做退出状', 'video_path': 'videos/signs/universal/tui_chu.mp4'},
    {'word': '打开', 'category': '通用词汇', 'description': '双手向外打开', 'video_path': 'videos/signs/universal/da_kai2.mp4'},
    {'word': '关闭', 'category': '通用词汇', 'description': '双手向内合拢', 'video_path': 'videos/signs/universal/guan_bi2.mp4'},
    {'word': '开始', 'category': '通用词汇', 'description': '右手向前指', 'video_path': 'videos/signs/universal/kai_shi2.mp4'},
    {'word': '结束', 'category': '通用词汇', 'description': '双手交叉', 'video_path': 'videos/signs/universal/jie_shu2.mp4'},
    {'word': '继续', 'category': '通用词汇', 'description': '右手向前挥动', 'video_path': 'videos/signs/universal/ji_xu2.mp4'},
    {'word': '停止', 'category': '通用词汇', 'description': '右手做停止手势', 'video_path': 'videos/signs/universal/ting_zhi2.mp4'},
    {'word': '等待', 'category': '通用词汇', 'description': '右手食指竖起', 'video_path': 'videos/signs/universal/deng_dai.mp4'},
    {'word': '出发', 'category': '通用词汇', 'description': '右手向前指', 'video_path': 'videos/signs/universal/chu_fa.mp4'},
    {'word': '返回', 'category': '通用词汇', 'description': '右手向后指', 'video_path': 'videos/signs/universal/fan_hui.mp4'},
    {'word': '到达', 'category': '通用词汇', 'description': '右手点地', 'video_path': 'videos/signs/universal/dao_da2.mp4'},
    {'word': '经过', 'category': '通用词汇', 'description': '右手从面前划过', 'video_path': 'videos/signs/universal/jing_guo.mp4'},
    {'word': '停留', 'category': '通用词汇', 'description': '右手停在原地', 'video_path': 'videos/signs/universal/ting_liu.mp4'},
    {'word': '移动', 'category': '通用词汇', 'description': '右手移动位置', 'video_path': 'videos/signs/universal/yi_dong.mp4'},
    {'word': '固定', 'category': '通用词汇', 'description': '右手固定不动', 'video_path': 'videos/signs/universal/gu_ding.mp4'},
    {'word': '变化', 'category': '通用词汇', 'description': '右手做波浪状', 'video_path': 'videos/signs/universal/bian_hua2.mp4'},
    {'word': '保持', 'category': '通用词汇', 'description': '右手保持原状', 'video_path': 'videos/signs/universal/bao_chi.mp4'},
    {'word': '改变', 'category': '通用词汇', 'description': '右手改变形状', 'video_path': 'videos/signs/universal/gai_bian.mp4'},
    {'word': '维持', 'category': '通用词汇', 'description': '右手保持原状', 'video_path': 'videos/signs/universal/wei_chi.mp4'},
    {'word': '调整', 'category': '通用词汇', 'description': '右手做微调状', 'video_path': 'videos/signs/universal/tiao_zheng.mp4'},
    {'word': '恢复', 'category': '通用词汇', 'description': '右手回到原状', 'video_path': 'videos/signs/universal/hui_fu.mp4'},
    {'word': '破坏', 'category': '通用词汇', 'description': '双手做撕碎状', 'video_path': 'videos/signs/universal/po_huai2.mp4'},
    {'word': '修复', 'category': '通用词汇', 'description': '双手做修补状', 'video_path': 'videos/signs/universal/xiu_fu.mp4'},
    {'word': '建立', 'category': '通用词汇', 'description': '双手做搭建状', 'video_path': 'videos/signs/universal/jian_li.mp4'},
    {'word': '拆除', 'category': '通用词汇', 'description': '双手做拆除状', 'video_path': 'videos/signs/universal/chai_chu.mp4'},
    {'word': '连接', 'category': '通用词汇', 'description': '双手食指连接', 'video_path': 'videos/signs/universal/lian_jie.mp4'},
    {'word': '断开', 'category': '通用词汇', 'description': '双手食指分开', 'video_path': 'videos/signs/universal/duan_kai.mp4'},
    {'word': '结合', 'category': '通用词汇', 'description': '双手合在一起', 'video_path': 'videos/signs/universal/jie_he.mp4'},
    {'word': '分离', 'category': '通用词汇', 'description': '双手分开', 'video_path': 'videos/signs/universal/fen_li.mp4'},
    {'word': '加入', 'category': '通用词汇', 'description': '右手加入左手', 'video_path': 'videos/signs/universal/jia_ru.mp4'},
    {'word': '退出', 'category': '通用词汇', 'description': '右手离开左手', 'video_path': 'videos/signs/universal/tui_chu2.mp4'},
    {'word': '包含', 'category': '通用词汇', 'description': '左手包住右手', 'video_path': 'videos/signs/universal/bao_han.mp4'},
    {'word': '排除', 'category': '通用词汇', 'description': '右手向外推', 'video_path': 'videos/signs/universal/pai_chu.mp4'},
    {'word': '吸收', 'category': '通用词汇', 'description': '右手做吸收状', 'video_path': 'videos/signs/universal/xi_shou.mp4'},
    {'word': '释放', 'category': '通用词汇', 'description': '双手向外张开', 'video_path': 'videos/signs/universal/shi_fang.mp4'},
    {'word': '收集', 'category': '通用词汇', 'description': '双手做收集状', 'video_path': 'videos/signs/universal/shou_ji.mp4'},
    {'word': '分散', 'category': '通用词汇', 'description': '双手向外散开', 'video_path': 'videos/signs/universal/fen_san.mp4'},
    {'word': '聚集', 'category': '通用词汇', 'description': '双手向中间聚拢', 'video_path': 'videos/signs/universal/ju_ji.mp4'},
    {'word': '分散', 'category': '通用词汇', 'description': '双手向外散开', 'video_path': 'videos/signs/universal/fen_san2.mp4'},
    {'word': '集中', 'category': '通用词汇', 'description': '双手向中间集中', 'video_path': 'videos/signs/universal/ji_zhong.mp4'},
    {'word': '分配', 'category': '通用词汇', 'description': '右手做分配状', 'video_path': 'videos/signs/universal/fen_pei.mp4'},
    {'word': '分享', 'category': '通用词汇', 'description': '右手做分享状', 'video_path': 'videos/signs/universal/fen_xiang.mp4'},
    {'word': '保留', 'category': '通用词汇', 'description': '右手做保留状', 'video_path': 'videos/signs/universal/bao_liu.mp4'},
    {'word': '放弃', 'category': '通用词汇', 'description': '右手做扔掉状', 'video_path': 'videos/signs/universal/fang_qi.mp4'},
    {'word': '保存', 'category': '通用词汇', 'description': '右手做保存状', 'video_path': 'videos/signs/universal/bao_cun.mp4'},
    {'word': '删除', 'category': '通用词汇', 'description': '右手做删除状', 'video_path': 'videos/signs/universal/shan_chu.mp4'},
    {'word': '记录', 'category': '通用词汇', 'description': '右手做记录状', 'video_path': 'videos/signs/universal/ji_lu.mp4'},
    {'word': '忘记', 'category': '通用词汇', 'description': '右手在额头前摆动', 'video_path': 'videos/signs/universal/wang_ji2.mp4'},
    {'word': '记住', 'category': '通用词汇', 'description': '右手点太阳穴', 'video_path': 'videos/signs/universal/ji_zhu.mp4'},
    {'word': '回忆', 'category': '通用词汇', 'description': '右手在太阳穴转圈', 'video_path': 'videos/signs/universal/hui_yi.mp4'},
    {'word': '忘记', 'category': '通用词汇', 'description': '右手在额头前摆动', 'video_path': 'videos/signs/universal/wang_ji3.mp4'},
    {'word': '提醒', 'category': '通用词汇', 'description': '右手点太阳穴', 'video_path': 'videos/signs/universal/ti_xing.mp4'},
    {'word': '忽略', 'category': '通用词汇', 'description': '右手挥手', 'video_path': 'videos/signs/universal/hu_lue.mp4'},
    {'word': '注意', 'category': '通用词汇', 'description': '右手点眼睛', 'video_path': 'videos/signs/universal/zhu_yi2.mp4'},
    {'word': '忽视', 'category': '通用词汇', 'description': '右手挥手', 'video_path': 'videos/signs/universal/hu_shi3.mp4'},
    {'word': '重视', 'category': '通用词汇', 'description': '右手握拳敲击', 'video_path': 'videos/signs/universal/zhong_shi.mp4'},
    {'word': '轻视', 'category': '通用词汇', 'description': '右手向下挥', 'video_path': 'videos/signs/universal/qing_shi.mp4'},
    {'word': '尊重', 'category': '通用词汇', 'description': '右手放在胸前鞠躬', 'video_path': 'videos/signs/universal/zun_zhong2.mp4'},
    {'word': '侮辱', 'category': '通用词汇', 'description': '右手向下指', 'video_path': 'videos/signs/universal/wu_ru.mp4'},
    {'word': '赞美', 'category': '通用词汇', 'description': '右手竖起拇指', 'video_path': 'videos/signs/universal/zan_mei.mp4'},
    {'word': '批评', 'category': '通用词汇', 'description': '右手食指指点', 'video_path': 'videos/signs/universal/pi_ping.mp4'},
    {'word': '表扬', 'category': '通用词汇', 'description': '右手竖起拇指', 'video_path': 'videos/signs/universal/biao_yang.mp4'},
    {'word': '责备', 'category': '通用词汇', 'description': '右手食指指点', 'video_path': 'videos/signs/universal/ze_bei.mp4'},
    {'word': '鼓励', 'category': '通用词汇', 'description': '双手向上托起', 'video_path': 'videos/signs/universal/gu_li.mp4'},
    {'word': '打击', 'category': '通用词汇', 'description': '右手向下敲击', 'video_path': 'videos/signs/universal/da_ji.mp4'},
    {'word': '支持', 'category': '通用词汇', 'description': '双手托起', 'video_path': 'videos/signs/universal/zhi_chi.mp4'},
    {'word': '反对', 'category': '通用词汇', 'description': '双手交叉', 'video_path': 'videos/signs/universal/fan_dui.mp4'},
    {'word': '同意', 'category': '通用词汇', 'description': '双手拇指竖起', 'video_path': 'videos/signs/universal/tong_yi2.mp4'},
    {'word': '不同意', 'category': '通用词汇', 'description': '双手食指交叉', 'video_path': 'videos/signs/universal/bu_tong_yi2.mp4'},
    {'word': '接受', 'category': '通用词汇', 'description': '双手做接收状', 'video_path': 'videos/signs/universal/jie_shou.mp4'},
    {'word': '拒绝', 'category': '通用词汇', 'description': '双手向外推', 'video_path': 'videos/signs/universal/ju_jue.mp4'},
    {'word': '允许', 'category': '通用词汇', 'description': '右手向前推', 'video_path': 'videos/signs/universal/yun_xu.mp4'},
    {'word': '禁止', 'category': '通用词汇', 'description': '右手做停止状', 'video_path': 'videos/signs/universal/jin_zhi.mp4'},
    {'word': '批准', 'category': '通用词汇', 'description': '右手做盖章状', 'video_path': 'videos/signs/universal/pi_zhun.mp4'},
    {'word': '否决', 'category': '通用词汇', 'description': '右手做划叉状', 'video_path': 'videos/signs/universal/fou_jue.mp4'},
    {'word': '确认', 'category': '通用词汇', 'description': '右手做打勾状', 'video_path': 'videos/signs/universal/que_ren.mp4'},
    {'word': '否认', 'category': '通用词汇', 'description': '右手食指摆动', 'video_path': 'videos/signs/universal/fou_ren.mp4'},
    {'word': '承认', 'category': '通用词汇', 'description': '右手拍胸口', 'video_path': 'videos/signs/universal/cheng_ren.mp4'},
    {'word': '否认', 'category': '通用词汇', 'description': '右手食指摆动', 'video_path': 'videos/signs/universal/fou_ren2.mp4'},
    {'word': '坦白', 'category': '通用词汇', 'description': '右手从胸口向前', 'video_path': 'videos/signs/universal/tan_bai.mp4'},
    {'word': '隐瞒', 'category': '通用词汇', 'description': '右手在嘴前遮挡', 'video_path': 'videos/signs/universal/yin_man.mp4'},
    {'word': '公开', 'category': '通用词汇', 'description': '双手向外打开', 'video_path': 'videos/signs/universal/gong_kai.mp4'},
    {'word': '秘密', 'category': '通用词汇', 'description': '右手在嘴前', 'video_path': 'videos/signs/universal/mi_mi.mp4'},
    {'word': '透明', 'category': '通用词汇', 'description': '双手做透明状', 'video_path': 'videos/signs/universal/tou_ming.mp4'},
    {'word': '隐蔽', 'category': '通用词汇', 'description': '右手做隐藏状', 'video_path': 'videos/signs/universal/yin_bi.mp4'},
    {'word': '明显', 'category': '通用词汇', 'description': '右手在眼前', 'video_path': 'videos/signs/universal/ming_xian.mp4'},
    {'word': '模糊', 'category': '通用词汇', 'description': '右手在眼前晃动', 'video_path': 'videos/signs/universal/mo_hu2.mp4'},
    {'word': '清楚', 'category': '通用词汇', 'description': '右手在眼前打开', 'video_path': 'videos/signs/universal/qing_chu2.mp4'},
    {'word': '混乱', 'category': '通用词汇', 'description': '双手乱挥', 'video_path': 'videos/signs/universal/hun_luan2.mp4'},
    {'word': '有序', 'category': '通用词汇', 'description': '右手依次排列', 'video_path': 'videos/signs/universal/you_xu.mp4'},
    {'word': '无序', 'category': '通用词汇', 'description': '双手乱挥', 'video_path': 'videos/signs/universal/wu_xu.mp4'},
    {'word': '整齐', 'category': '通用词汇', 'description': '右手依次排列', 'video_path': 'videos/signs/universal/zheng_qi2.mp4'},
    {'word': '杂乱', 'category': '通用词汇', 'description': '双手乱挥', 'video_path': 'videos/signs/universal/za_luan2.mp4'},
    {'word': '干净', 'category': '通用词汇', 'description': '右手做擦拭状', 'video_path': 'videos/signs/universal/gan_jing2.mp4'},
    {'word': '肮脏', 'category': '通用词汇', 'description': '右手做甩脏东西状', 'video_path': 'videos/signs/universal/ang_zang2.mp4'},
    {'word': '新鲜', 'category': '通用词汇', 'description': '右手在鼻子前扇风', 'video_path': 'videos/signs/universal/xin_xian2.mp4'},
    {'word': '陈旧', 'category': '通用词汇', 'description': '右手做拍灰尘状', 'video_path': 'videos/signs/universal/chen_jiu2.mp4'},
    {'word': '现代', 'category': '通用词汇', 'description': '右手做按手机状', 'video_path': 'videos/signs/universal/xian_dai2.mp4'},
    {'word': '古老', 'category': '通用词汇', 'description': '右手做写毛笔字状', 'video_path': 'videos/signs/universal/gu_lao.mp4'},
    {'word': '流行', 'category': '通用词汇', 'description': '右手做波浪状移动', 'video_path': 'videos/signs/universal/liu_xing2.mp4'},
    {'word': '过时', 'category': '通用词汇', 'description': '右手向后指', 'video_path': 'videos/signs/universal/guo_shi2.mp4'},
    {'word': '时尚', 'category': '通用词汇', 'description': '右手在身前划圈', 'video_path': 'videos/signs/universal/shi_shang2.mp4'},
    {'word': '传统', 'category': '通用词汇', 'description': '右手做写毛笔字状', 'video_path': 'videos/signs/universal/chuan_tong2.mp4'},
    {'word': '创新', 'category': '通用词汇', 'description': '右手做创造状', 'video_path': 'videos/signs/universal/chuang_xin.mp4'},
    {'word': '保守', 'category': '通用词汇', 'description': '双手抱胸', 'video_path': 'videos/signs/universal/bao_shou.mp4'},
    {'word': '开放', 'category': '通用词汇', 'description': '双手向外打开', 'video_path': 'videos/signs/universal/kai_fang.mp4'},
    {'word': '封闭', 'category': '通用词汇', 'description': '双手做围墙状', 'video_path': 'videos/signs/universal/feng_bi.mp4'},
    {'word': '自由', 'category': '通用词汇', 'description': '双手向上张开', 'video_path': 'videos/signs/universal/zi_you2.mp4'},
    {'word': '限制', 'category': '通用词汇', 'description': '双手做限制状', 'video_path': 'videos/signs/universal/xian_zhi.mp4'},
    {'word': '平等', 'category': '通用词汇', 'description': '双手手心向下，保持水平', 'video_path': 'videos/signs/universal/ping_deng2.mp4'},
    {'word': '不平等', 'category': '通用词汇', 'description': '双手一高一低', 'video_path': 'videos/signs/universal/bu_ping_deng.mp4'},
    {'word': '公平', 'category': '通用词汇', 'description': '双手做天平状', 'video_path': 'videos/signs/universal/gong_ping2.mp4'},
    {'word': '不公平', 'category': '通用词汇', 'description': '双手倾斜', 'video_path': 'videos/signs/universal/bu_gong_ping.mp4'},
    {'word': '正义', 'category': '通用词汇', 'description': '右手握拳在胸前', 'video_path': 'videos/signs/universal/zheng_yi2.mp4'},
    {'word': '邪恶', 'category': '通用词汇', 'description': '右手做爪状', 'video_path': 'videos/signs/universal/xie_e.mp4'},
    {'word': '善良', 'category': '通用词汇', 'description': '右手放在心口', 'video_path': 'videos/signs/universal/shan_liang.mp4'},
    {'word': '凶恶', 'category': '通用词汇', 'description': '右手做爪状', 'video_path': 'videos/signs/universal/xiong_e.mp4'},
    {'word': '温柔', 'category': '通用词汇', 'description': '右手做抚摸状', 'video_path': 'videos/signs/universal/wen_rou.mp4'},
    {'word': '粗暴', 'category': '通用词汇', 'description': '右手做打击状', 'video_path': 'videos/signs/universal/cu_bao.mp4'},
    {'word': '耐心', 'category': '通用词汇', 'description': '右手慢慢移动', 'video_path': 'videos/signs/universal/nai_xin.mp4'},
    {'word': '急躁', 'category': '通用词汇', 'description': '双手快速挥动', 'video_path': 'videos/signs/universal/ji_zao.mp4'},
    {'word': '细心', 'category': '通用词汇', 'description': '右手做细致状', 'video_path': 'videos/signs/universal/xi_xin.mp4'},
    {'word': '粗心', 'category': '通用词汇', 'description': '右手做大意状', 'video_path': 'videos/signs/universal/cu_xin.mp4'},
    {'word': '谨慎', 'category': '通用词汇', 'description': '右手小心翼翼', 'video_path': 'videos/signs/universal/jin_shen.mp4'},
    {'word': '大胆', 'category': '通用词汇', 'description': '右手大胆向前', 'video_path': 'videos/signs/universal/da_dan.mp4'},
    {'word': '谦虚', 'category': '通用词汇', 'description': '右手向下', 'video_path': 'videos/signs/universal/qian_xu.mp4'},
    {'word': '骄傲', 'category': '通用词汇', 'description': '右手向上', 'video_path': 'videos/signs/universal/jiao_ao2.mp4'},
    {'word': '诚实', 'category': '通用词汇', 'description': '右手放在胸口', 'video_path': 'videos/signs/universal/cheng_shi2.mp4'},
    {'word': '虚伪', 'category': '通用词汇', 'description': '右手做面具状', 'video_path': 'videos/signs/universal/xu_wei.mp4'},
    {'word': '真诚', 'category': '通用词汇', 'description': '右手放在胸口', 'video_path': 'videos/signs/universal/zhen_cheng.mp4'},
    {'word': '虚假', 'category': '通用词汇', 'description': '右手做面具状', 'video_path': 'videos/signs/universal/xu_jia.mp4'},
    {'word': '直接', 'category': '通用词汇', 'description': '右手直线向前', 'video_path': 'videos/signs/universal/zhi_jie.mp4'},
    {'word': '间接', 'category': '通用词汇', 'description': '右手曲线向前', 'video_path': 'videos/signs/universal/jian_jie.mp4'},
    {'word': '公开', 'category': '通用词汇', 'description': '双手向外打开', 'video_path': 'videos/signs/universal/gong_kai2.mp4'},
    {'word': '私下', 'category': '通用词汇', 'description': '右手在嘴边', 'video_path': 'videos/signs/universal/si_xia.mp4'},
    {'word': '正式', 'category': '通用词汇', 'description': '右手做正式状', 'video_path': 'videos/signs/universal/zheng_shi.mp4'},
    {'word': '非正式', 'category': '通用词汇', 'description': '右手做随意状', 'video_path': 'videos/signs/universal/fei_zheng_shi.mp4'},
    {'word': '官方', 'category': '通用词汇', 'description': '右手做盖章状', 'video_path': 'videos/signs/universal/guan_fang.mp4'},
    {'word': '民间', 'category': '通用词汇', 'description': '右手做民众状', 'video_path': 'videos/signs/universal/min_jian.mp4'},
    {'word': '公共', 'category': '通用词汇', 'description': '双手张开', 'video_path': 'videos/signs/universal/gong_gong.mp4'},
    {'word': '私人', 'category': '通用词汇', 'description': '右手指自己', 'video_path': 'videos/signs/universal/si_ren.mp4'},
    {'word': '集体', 'category': '通用词汇', 'description': '双手合拢', 'video_path': 'videos/signs/universal/ji_ti.mp4'},
    {'word': '个人', 'category': '通用词汇', 'description': '右手指自己', 'video_path': 'videos/signs/universal/ge_ren.mp4'},
    {'word': '团体', 'category': '通用词汇', 'description': '双手合拢', 'video_path': 'videos/signs/universal/tuan_ti.mp4'},
    {'word': '个体', 'category': '通用词汇', 'description': '右手指自己', 'video_path': 'videos/signs/universal/ge_ti.mp4'},
    {'word': '组织', 'category': '通用词汇', 'description': '双手做组织状', 'video_path': 'videos/signs/universal/zu_zhi.mp4'},
    {'word': '成员', 'category': '通用词汇', 'description': '右手指自己', 'video_path': 'videos/signs/universal/cheng_yuan.mp4'},
    {'word': '领导', 'category': '通用词汇', 'description': '右手向前指', 'video_path': 'videos/signs/universal/ling_dao.mp4'},
    {'word': '群众', 'category': '通用词汇', 'description': '双手张开', 'video_path': 'videos/signs/universal/qun_zhong.mp4'},
    {'word': '上级', 'category': '通用词汇', 'description': '右手向上指', 'video_path': 'videos/signs/universal/shang_ji.mp4'},
    {'word': '下级', 'category': '通用词汇', 'description': '右手向下指', 'video_path': 'videos/signs/universal/xia_ji.mp4'},
    {'word': '平等', 'category': '通用词汇', 'description': '双手手心向下，保持水平', 'video_path': 'videos/signs/universal/ping_deng3.mp4'},
    {'word': '等级', 'category': '通用词汇', 'description': '右手依次向上', 'video_path': 'videos/signs/universal/deng_ji.mp4'},
    {'word': '权威', 'category': '通用词汇', 'description': '右手握拳在胸前', 'video_path': 'videos/signs/universal/quan_wei.mp4'},
    {'word': '服从', 'category': '通用词汇', 'description': '右手向下', 'video_path': 'videos/signs/universal/fu_cong.mp4'},
    {'word': '反抗', 'category': '通用词汇', 'description': '右手向上反抗', 'video_path': 'videos/signs/universal/fan_kang.mp4'},
    {'word': '统治', 'category': '通用词汇', 'description': '右手向下压制', 'video_path': 'videos/signs/universal/tong_zhi.mp4'},
    {'word': '被统治', 'category': '通用词汇', 'description': '右手向下被压制', 'video_path': 'videos/signs/universal/bei_tong_zhi.mp4'},
    {'word': '独立', 'category': '通用词汇', 'description': '右手单独站立', 'video_path': 'videos/signs/universal/du_li.mp4'},
    {'word': '依赖', 'category': '通用词汇', 'description': '右手依靠左手', 'video_path': 'videos/signs/universal/yi_lai.mp4'},
    {'word': '自主', 'category': '通用词汇', 'description': '右手拍胸口', 'video_path': 'videos/signs/universal/zi_zhu.mp4'},
    {'word': '受控', 'category': '通用词汇', 'description': '右手被左手控制', 'video_path': 'videos/signs/universal/shou_kong.mp4'},
    {'word': '自由', 'category': '通用词汇', 'description': '双手向上张开', 'video_path': 'videos/signs/universal/zi_you3.mp4'},
    {'word': '约束', 'category': '通用词汇', 'description': '双手做限制状', 'video_path': 'videos/signs/universal/yue_shu.mp4'},
    {'word': '权利', 'category': '通用词汇', 'description': '右手握拳举起', 'video_path': 'videos/signs/universal/quan_li2.mp4'},
    {'word': '义务', 'category': '通用词汇', 'description': '右手做承诺状', 'video_path': 'videos/signs/universal/yi_wu3.mp4'},
    {'word': '责任', 'category': '通用词汇', 'description': '右手拍肩膀', 'video_path': 'videos/signs/universal/ze_ren2.mp4'},
    {'word': '权力', 'category': '通用词汇', 'description': '右手握拳', 'video_path': 'videos/signs/universal/quan_li3.mp4'},
    {'word': '民主', 'category': '通用词汇', 'description': '双手做投票状', 'video_path': 'videos/signs/universal/min_zhu.mp4'},
    {'word': '专制', 'category': '通用词汇', 'description': '右手向下压制', 'video_path': 'videos/signs/universal/zhuan_zhi.mp4'},
    {'word': '法治', 'category': '通用词汇', 'description': '右手做敲法槌状', 'video_path': 'videos/signs/universal/fa_zhi.mp4'},
    {'word': '人治', 'category': '通用词汇', 'description': '右手指自己', 'video_path': 'videos/signs/universal/ren_zhi.mp4'},
    {'word': '文明', 'category': '通用词汇', 'description': '右手做礼貌状', 'video_path': 'videos/signs/universal/wen_ming.mp4'},
    {'word': '野蛮', 'category': '通用词汇', 'description': '右手做粗鲁状', 'video_path': 'videos/signs/universal/ye_man.mp4'},
    {'word': '进步', 'category': '通用词汇', 'description': '右手向上移动', 'video_path': 'videos/signs/universal/jin_bu2.mp4'},
    {'word': '退步', 'category': '通用词汇', 'description': '右手向下移动', 'video_path': 'videos/signs/universal/tui_bu2.mp4'},
    {'word': '发展', 'category': '通用词汇', 'description': '双手向上展开', 'video_path': 'videos/signs/universal/fa_zhan2.mp4'},
    {'word': '停滞', 'category': '通用词汇', 'description': '右手停止不动', 'video_path': 'videos/signs/universal/ting_zhi3.mp4'},
    {'word': '繁荣', 'category': '通用词汇', 'description': '双手向上开花状', 'video_path': 'videos/signs/universal/fan_rong.mp4'},
    {'word': '萧条', 'category': '通用词汇', 'description': '双手向下', 'video_path': 'videos/signs/universal/xiao_tiao.mp4'},
    {'word': '富裕', 'category': '通用词汇', 'description': '右手做数钱状', 'video_path': 'videos/signs/universal/fu_yu2.mp4'},
    {'word': '贫穷', 'category': '通用词汇', 'description': '右手做乞讨状', 'video_path': 'videos/signs/universal/pin_qiong2.mp4'},
    {'word': '先进', 'category': '通用词汇', 'description': '右手向前指', 'video_path': 'videos/signs/universal/xian_jin.mp4'},
    {'word': '落后', 'category': '通用词汇', 'description': '右手向后指', 'video_path': 'videos/signs/universal/luo_hou2.mp4'},
    {'word': '现代', 'category': '通用词汇', 'description': '右手做按手机状', 'video_path': 'videos/signs/universal/xian_dai3.mp4'},
    {'word': '传统', 'category': '通用词汇', 'description': '右手做写毛笔字状', 'video_path': 'videos/signs/universal/chuan_tong3.mp4'},
    {'word': '开放', 'category': '通用词汇', 'description': '双手向外打开', 'video_path': 'videos/signs/universal/kai_fang2.mp4'},
    {'word': '封闭', 'category': '通用词汇', 'description': '双手做围墙状', 'video_path': 'videos/signs/universal/feng_bi2.mp4'},
    {'word': '国际', 'category': '通用词汇', 'description': '双手画大圈', 'video_path': 'videos/signs/universal/guo_ji.mp4'},
    {'word': '国内', 'category': '通用词汇', 'description': '右手在胸前画圈', 'video_path': 'videos/signs/universal/guo_nei.mp4'},
    {'word': '世界', 'category': '通用词汇', 'description': '双手画大圈', 'video_path': 'videos/signs/universal/shi_jie2.mp4'},
    {'word': '地方', 'category': '通用词汇', 'description': '右手向下指', 'video_path': 'videos/signs/universal/di_fang.mp4'},
    {'word': '全球', 'category': '通用词汇', 'description': '双手做地球状', 'video_path': 'videos/signs/universal/quan_qiu.mp4'},
    {'word': '局部', 'category': '通用词汇', 'description': '右手指一部分', 'video_path': 'videos/signs/universal/ju_bu.mp4'},
    {'word': '整体', 'category': '通用词汇', 'description': '双手画圈', 'video_path': 'videos/signs/universal/zheng_ti.mp4'},
    {'word': '部分', 'category': '通用词汇', 'description': '右手指一部分', 'video_path': 'videos/signs/universal/bu_fen2.mp4'},
    {'word': '全部', 'category': '通用词汇', 'description': '双手张开', 'video_path': 'videos/signs/universal/quan_bu2.mp4'},
    {'word': '多数', 'category': '通用词汇', 'description': '右手表示多', 'video_path': 'videos/signs/universal/duo_shu.mp4'},
    {'word': '少数', 'category': '通用词汇', 'description': '右手表示少', 'video_path': 'videos/signs/universal/shao_shu.mp4'},
    {'word': '一半', 'category': '通用词汇', 'description': '右手做一半手势', 'video_path': 'videos/signs/universal/yi_ban2.mp4'},
    {'word': '双倍', 'category': '通用词汇', 'description': '右手表示两倍', 'video_path': 'videos/signs/universal/shuang_bei.mp4'},
    {'word': '单个', 'category': '通用词汇', 'description': '右手食指竖起', 'video_path': 'videos/signs/universal/dan_ge.mp4'},
    {'word': '多个', 'category': '通用词汇', 'description': '右手表示多个', 'video_path': 'videos/signs/universal/duo_ge.mp4'},
    {'word': '无限', 'category': '通用词汇', 'description': '双手画大圈', 'video_path': 'videos/signs/universal/wu_xian.mp4'},
    {'word': '有限', 'category': '通用词汇', 'description': '双手做限制状', 'video_path': 'videos/signs/universal/you_xian.mp4'},
    {'word': '永久', 'category': '通用词汇', 'description': '右手画大圈', 'video_path': 'videos/signs/universal/yong_jiu.mp4'},
    {'word': '暂时', 'category': '通用词汇', 'description': '右手做短暂状', 'video_path': 'videos/signs/universal/zan_shi.mp4'},
    {'word': '长期', 'category': '通用词汇', 'description': '右手做长期状', 'video_path': 'videos/signs/universal/chang_qi.mp4'},
    {'word': '短期', 'category': '通用词汇', 'description': '右手做短期状', 'video_path': 'videos/signs/universal/duan_qi.mp4'},
    {'word': '永远', 'category': '通用词汇', 'description': '右手画大圈', 'video_path': 'videos/signs/universal/yong_yuan2.mp4'},
  ];

  // 日常交流 (40个)
  static List<Map<String, String>> dailyWords = [
    {'word': '早上好', 'category': '日常交流', 'description': '右手从右向上划弧线，表示太阳升起', 'video_path': 'videos/signs/daily/zao_shang_hao.mp4'},
    {'word': '晚上好', 'category': '日常交流', 'description': '右手从上向下划弧线，表示太阳落山', 'video_path': 'videos/signs/daily/wan_shang_hao.mp4'},
    {'word': '晚安', 'category': '日常交流', 'description': '双手合十放在脸颊旁，做睡觉状', 'video_path': 'videos/signs/daily/wan_an.mp4'},
    {'word': '名字', 'category': '日常交流', 'description': '右手食指指向嘴巴，然后向前', 'video_path': 'videos/signs/daily/ming_zi.mp4'},
    {'word': '叫什么', 'category': '日常交流', 'description': '右手食指指嘴，然后做询问状', 'video_path': 'videos/signs/daily/jiao_shen_me.mp4'},
    {'word': '年龄', 'category': '日常交流', 'description': '右手食指在脸旁划圈', 'video_path': 'videos/signs/daily/nian_ling.mp4'},
    {'word': '多大', 'category': '日常交流', 'description': '双手向两边张开，做询问状', 'video_path': 'videos/signs/daily/duo_da.mp4'},
    {'word': '哪里', 'category': '日常交流', 'description': '右手食指左右摆动，做询问状', 'video_path': 'videos/signs/daily/na_li.mp4'},
    {'word': '什么', 'category': '日常交流', 'description': '右手手心向上，左右摆动', 'video_path': 'videos/signs/daily/shen_me.mp4'},
    {'word': '为什么', 'category': '日常交流', 'description': '右手食指指向太阳穴，然后向外', 'video_path': 'videos/signs/daily/wei_shen_me.mp4'},
    {'word': '怎么样', 'category': '日常交流', 'description': '双手手心向上，上下移动', 'video_path': 'videos/signs/daily/zen_me_yang.mp4'},
    {'word': '多少钱', 'category': '日常交流', 'description': '右手做数钱状', 'video_path': 'videos/signs/daily/duo_shao_qian.mp4'},
    {'word': '贵', 'category': '日常交流', 'description': '右手向上举，表示价格高', 'video_path': 'videos/signs/daily/gui.mp4'},
    {'word': '便宜', 'category': '日常交流', 'description': '右手向下压，表示价格低', 'video_path': 'videos/signs/daily/pian_yi.mp4'},
    {'word': '买', 'category': '日常交流', 'description': '右手做抓取后拿回的动作', 'video_path': 'videos/signs/daily/mai.mp4'},
    {'word': '卖', 'category': '日常交流', 'description': '右手做递出的动作', 'video_path': 'videos/signs/daily/mai_chu.mp4'},
    {'word': '给', 'category': '日常交流', 'description': '右手手心向上，向前推', 'video_path': 'videos/signs/daily/gei.mp4'},
    {'word': '拿', 'category': '日常交流', 'description': '右手做抓取动作', 'video_path': 'videos/signs/daily/na.mp4'},
    {'word': '放', 'category': '日常交流', 'description': '右手向下放的动作', 'video_path': 'videos/signs/daily/fang.mp4'},
    {'word': '找', 'category': '日常交流', 'description': '右手食指在空中搜寻', 'video_path': 'videos/signs/daily/zhao.mp4'},
    {'word': '看', 'category': '日常交流', 'description': '右手食指和中指指向眼睛再向前', 'video_path': 'videos/signs/daily/kan.mp4'},
    {'word': '听', 'category': '日常交流', 'description': '右手食指指向耳朵', 'video_path': 'videos/signs/daily/ting.mp4'},
    {'word': '说', 'category': '日常交流', 'description': '右手食指从嘴边向前', 'video_path': 'videos/signs/daily/shuo.mp4'},
    {'word': '写', 'category': '日常交流', 'description': '右手做书写动作', 'video_path': 'videos/signs/daily/xie.mp4'},
    {'word': '读', 'category': '日常交流', 'description': '右手在嘴前做翻书状', 'video_path': 'videos/signs/daily/du.mp4'},
    {'word': '打电话', 'category': '日常交流', 'description': '右手做打电话手势放在耳边', 'video_path': 'videos/signs/daily/da_dian_hua.mp4'},
    {'word': '发短信', 'category': '日常交流', 'description': '双手做打字状', 'video_path': 'videos/signs/daily/fa_duan_xin.mp4'},
    {'word': '上网', 'category': '日常交流', 'description': '双手食指交替向上', 'video_path': 'videos/signs/daily/shang_wang.mp4'},
    {'word': '工作', 'category': '日常交流', 'description': '双手握拳，上下移动', 'video_path': 'videos/signs/daily/gong_zuo.mp4'},
    {'word': '学习', 'category': '日常交流', 'description': '双手在头顶做翻书状', 'video_path': 'videos/signs/daily/xue_xi.mp4'},
    {'word': '休息', 'category': '日常交流', 'description': '双手放松，向下垂', 'video_path': 'videos/signs/daily/xiu_xi.mp4'},
    {'word': '睡觉', 'category': '日常交流', 'description': '双手合十放在脸颊旁', 'video_path': 'videos/signs/daily/shui_jiao.mp4'},
    {'word': '起床', 'category': '日常交流', 'description': '右手从下向上举', 'video_path': 'videos/signs/daily/qi_chuang.mp4'},
    {'word': '洗脸', 'category': '日常交流', 'description': '双手在脸前做洗脸动作', 'video_path': 'videos/signs/daily/xi_lian.mp4'},
    {'word': '刷牙', 'category': '日常交流', 'description': '右手在嘴前做刷牙动作', 'video_path': 'videos/signs/daily/shua_ya.mp4'},
    {'word': '洗澡', 'category': '日常交流', 'description': '双手在身上做搓洗动作', 'video_path': 'videos/signs/daily/xi_zao.mp4'},
    {'word': '穿衣服', 'category': '日常交流', 'description': '双手做穿衣动作', 'video_path': 'videos/signs/daily/chuan_yi_fu.mp4'},
    {'word': '脱衣服', 'category': '日常交流', 'description': '双手做脱衣动作', 'video_path': 'videos/signs/daily/tuo_yi_fu.mp4'},
    {'word': '开门', 'category': '日常交流', 'description': '右手做开门动作', 'video_path': 'videos/signs/daily/kai_men.mp4'},
    {'word': '关门', 'category': '日常交流', 'description': '右手做关门动作', 'video_path': 'videos/signs/daily/guan_men.mp4'},
  ];

  // 情绪表达 (40个)
  static List<Map<String, String>> emotionWords = [
    {'word': '高兴', 'category': '情绪表达', 'description': '双手在胸前向上挥动，脸带笑容', 'video_path': 'videos/signs/emotion/gao_xing.mp4'},
    {'word': '开心', 'category': '情绪表达', 'description': '右手在胸前打圈，表示心情好', 'video_path': 'videos/signs/emotion/kai_xin.mp4'},
    {'word': '快乐', 'category': '情绪表达', 'description': '双手向上跳跃式挥动', 'video_path': 'videos/signs/emotion/kuai_le.mp4'},
    {'word': '幸福', 'category': '情绪表达', 'description': '右手拍胸口，露出笑容', 'video_path': 'videos/signs/emotion/xing_fu.mp4'},
    {'word': '伤心', 'category': '情绪表达', 'description': '双手从眼睛向下滑，模仿流泪', 'video_path': 'videos/signs/emotion/shang_xin.mp4'},
    {'word': '难过', 'category': '情绪表达', 'description': '右手在心口位置向下按', 'video_path': 'videos/signs/emotion/nan_guo.mp4'},
    {'word': '痛苦', 'category': '情绪表达', 'description': '双手握拳在胸前挤压', 'video_path': 'videos/signs/emotion/tong_ku.mp4'},
    {'word': '生气', 'category': '情绪表达', 'description': '右手握拳在胸前用力敲', 'video_path': 'videos/signs/emotion/sheng_qi.mp4'},
    {'word': '愤怒', 'category': '情绪表达', 'description': '双手握拳，激烈向上挥', 'video_path': 'videos/signs/emotion/fen_nu.mp4'},
    {'word': '害怕', 'category': '情绪表达', 'description': '双手在胸前颤抖', 'video_path': 'videos/signs/emotion/hai_pa.mp4'},
    {'word': '紧张', 'category': '情绪表达', 'description': '双手握紧，身体前倾', 'video_path': 'videos/signs/emotion/jin_zhang.mp4'},
    {'word': '担心', 'category': '情绪表达', 'description': '右手在额头前摆动', 'video_path': 'videos/signs/emotion/dan_xin.mp4'},
    {'word': '着急', 'category': '情绪表达', 'description': '双手快速交替挥动', 'video_path': 'videos/signs/emotion/zhao_ji.mp4'},
    {'word': '焦虑', 'category': '情绪表达', 'description': '双手在胸前不停搓动', 'video_path': 'videos/signs/emotion/jiao_lv.mp4'},
    {'word': '放松', 'category': '情绪表达', 'description': '双手从紧握到张开', 'video_path': 'videos/signs/emotion/fang_song.mp4'},
    {'word': '平静', 'category': '情绪表达', 'description': '双手平稳向下按', 'video_path': 'videos/signs/emotion/ping_jing.mp4'},
    {'word': '激动', 'category': '情绪表达', 'description': '双手在胸前快速上下挥动', 'video_path': 'videos/signs/emotion/ji_dong.mp4'},
    {'word': '兴奋', 'category': '情绪表达', 'description': '双手握拳向上跳跃', 'video_path': 'videos/signs/emotion/xing_fen.mp4'},
    {'word': '惊讶', 'category': '情绪表达', 'description': '双手在脸颊旁向外张开', 'video_path': 'videos/signs/emotion/jing_ya.mp4'},
    {'word': '好奇', 'category': '情绪表达', 'description': '右手食指在下巴处转圈', 'video_path': 'videos/signs/emotion/hao_qi.mp4'},
    {'word': '疑惑', 'category': '情绪表达', 'description': '右手食指在太阳穴处转圈', 'video_path': 'videos/signs/emotion/yi_huo.mp4'},
    {'word': '困惑', 'category': '情绪表达', 'description': '双手在头顶交替画圈', 'video_path': 'videos/signs/emotion/kun_huo.mp4'},
    {'word': '无聊', 'category': '情绪表达', 'description': '右手在嘴前打哈欠状', 'video_path': 'videos/signs/emotion/wu_liao.mp4'},
    {'word': '厌烦', 'category': '情绪表达', 'description': '右手在面前挥动，表示不耐烦', 'video_path': 'videos/signs/emotion/yan_fan.mp4'},
    {'word': '害羞', 'category': '情绪表达', 'description': '双手捂脸，表示不好意思', 'video_path': 'videos/signs/emotion/hai_xiu.mp4'},
    {'word': '尴尬', 'category': '情绪表达', 'description': '右手在额头擦汗状', 'video_path': 'videos/signs/emotion/gan_ga.mp4'},
    {'word': '失望', 'category': '情绪表达', 'description': '双手向下摊开，摇头', 'video_path': 'videos/signs/emotion/shi_wang.mp4'},
    {'word': '绝望', 'category': '情绪表达', 'description': '双手握拳砸向胸口', 'video_path': 'videos/signs/emotion/jue_wang.mp4'},
    {'word': '满足', 'category': '情绪表达', 'description': '右手在胸前画圈，表示充实', 'video_path': 'videos/signs/emotion/man_zu.mp4'},
    {'word': '感激', 'category': '情绪表达', 'description': '双手合十放在胸前', 'video_path': 'videos/signs/emotion/gan_ji.mp4'},
    {'word': '骄傲', 'category': '情绪表达', 'description': '右手拍胸口，昂头', 'video_path': 'videos/signs/emotion/jiao_ao.mp4'},
    {'word': '嫉妒', 'category': '情绪表达', 'description': '右手在眼前做偷看状', 'video_path': 'videos/signs/emotion/ji_du.mp4'},
    {'word': '羡慕', 'category': '情绪表达', 'description': '双手放在下巴，做向往状', 'video_path': 'videos/signs/emotion/xian_mu.mp4'},
    {'word': '孤独', 'category': '情绪表达', 'description': '双手抱肩，低头', 'video_path': 'videos/signs/emotion/gu_du.mp4'},
    {'word': '寂寞', 'category': '情绪表达', 'description': '右手在胸前画圈，表示空虚', 'video_path': 'videos/signs/emotion/ji_mo.mp4'},
    {'word': '思念', 'category': '情绪表达', 'description': '右手放在心口，向前伸手', 'video_path': 'videos/signs/emotion/si_nian.mp4'},
    {'word': '想念', 'category': '情绪表达', 'description': '双手在胸前交叉，表示牵挂', 'video_path': 'videos/signs/emotion/xiang_nian.mp4'},
    {'word': '感动', 'category': '情绪表达', 'description': '双手在眼前做擦泪状', 'video_path': 'videos/signs/emotion/gan_dong.mp4'},
    {'word': '惊喜', 'category': '情绪表达', 'description': '双手捂嘴，眼睛睁大', 'video_path': 'videos/signs/emotion/jing_xi.mp4'},
    {'word': '平静', 'category': '情绪表达', 'description': '双手从胸前向下按，深呼吸', 'video_path': 'videos/signs/emotion/ping_jing2.mp4'},
  ];

  // 数字时间 (51个 = 11个数字 + 40个时间)
  static List<Map<String, String>> numberTimeWords = [
    // 数字 0-10 (11个)
    {'word': '0', 'category': '数字时间', 'description': '右手握拳，拳心向自己', 'video_path': 'videos/signs/number_time/ling.mp4'},
    {'word': '1', 'category': '数字时间', 'description': '右手食指竖起', 'video_path': 'videos/signs/number_time/yi.mp4'},
    {'word': '2', 'category': '数字时间', 'description': '右手食指和中指竖起', 'video_path': 'videos/signs/number_time/er.mp4'},
    {'word': '3', 'category': '数字时间', 'description': '右手食指、中指、无名指竖起', 'video_path': 'videos/signs/number_time/san.mp4'},
    {'word': '4', 'category': '数字时间', 'description': '右手四指竖起，拇指弯曲', 'video_path': 'videos/signs/number_time/si.mp4'},
    {'word': '5', 'category': '数字时间', 'description': '右手五指张开', 'video_path': 'videos/signs/number_time/wu.mp4'},
    {'word': '6', 'category': '数字时间', 'description': '右手拇指和小指伸出', 'video_path': 'videos/signs/number_time/liu.mp4'},
    {'word': '7', 'category': '数字时间', 'description': '右手拇指、食指、中指捏在一起', 'video_path': 'videos/signs/number_time/qi.mp4'},
    {'word': '8', 'category': '数字时间', 'description': '右手拇指和食指伸出成"L"形', 'video_path': 'videos/signs/number_time/ba.mp4'},
    {'word': '9', 'category': '数字时间', 'description': '右手食指弯曲成钩状', 'video_path': 'videos/signs/number_time/jiu.mp4'},
    {'word': '10', 'category': '数字时间', 'description': '右手握拳，然后伸出食指交叉', 'video_path': 'videos/signs/number_time/shi.mp4'},

    // 时间相关 (40个)
    {'word': '时间', 'category': '数字时间', 'description': '右手食指在左手腕画圈', 'video_path': 'videos/signs/number_time/shi_jian.mp4'},
    {'word': '现在', 'category': '数字时间', 'description': '右手食指向下指地面', 'video_path': 'videos/signs/number_time/xian_zai.mp4'},
    {'word': '今天', 'category': '数字时间', 'description': '右手食指向下指，然后画圆', 'video_path': 'videos/signs/number_time/jin_tian.mp4'},
    {'word': '明天', 'category': '数字时间', 'description': '右手向前指，表示未来', 'video_path': 'videos/signs/number_time/ming_tian.mp4'},
    {'word': '昨天', 'category': '数字时间', 'description': '右手向后指，表示过去', 'video_path': 'videos/signs/number_time/zuo_tian.mp4'},
    {'word': '星期', 'category': '数字时间', 'description': '右手食指在左手掌画圈', 'video_path': 'videos/signs/number_time/xing_qi.mp4'},
    {'word': '星期一', 'category': '数字时间', 'description': '先做星期手势，然后做数字1', 'video_path': 'videos/signs/number_time/xing_qi_yi.mp4'},
    {'word': '星期二', 'category': '数字时间', 'description': '先做星期手势，然后做数字2', 'video_path': 'videos/signs/number_time/xing_qi_er.mp4'},
    {'word': '星期三', 'category': '数字时间', 'description': '先做星期手势，然后做数字3', 'video_path': 'videos/signs/number_time/xing_qi_san.mp4'},
    {'word': '星期四', 'category': '数字时间', 'description': '先做星期手势，然后做数字4', 'video_path': 'videos/signs/number_time/xing_qi_si.mp4'},
    {'word': '星期五', 'category': '数字时间', 'description': '先做星期手势，然后做数字5', 'video_path': 'videos/signs/number_time/xing_qi_wu.mp4'},
    {'word': '星期六', 'category': '数字时间', 'description': '先做星期手势，然后做数字6', 'video_path': 'videos/signs/number_time/xing_qi_liu.mp4'},
    {'word': '星期日', 'category': '数字时间', 'description': '先做星期手势，然后做数字7', 'video_path': 'videos/signs/number_time/xing_qi_ri.mp4'},
    {'word': '月', 'category': '数字时间', 'description': '右手食指画月牙形', 'video_path': 'videos/signs/number_time/yue.mp4'},
    {'word': '一月', 'category': '数字时间', 'description': '先做月手势，然后做数字1', 'video_path': 'videos/signs/number_time/yi_yue.mp4'},
    {'word': '二月', 'category': '数字时间', 'description': '先做月手势，然后做数字2', 'video_path': 'videos/signs/number_time/er_yue.mp4'},
    {'word': '三月', 'category': '数字时间', 'description': '先做月手势，然后做数字3', 'video_path': 'videos/signs/number_time/san_yue.mp4'},
    {'word': '四月', 'category': '数字时间', 'description': '先做月手势，然后做数字4', 'video_path': 'videos/signs/number_time/si_yue.mp4'},
    {'word': '五月', 'category': '数字时间', 'description': '先做月手势，然后做数字5', 'video_path': 'videos/signs/number_time/wu_yue.mp4'},
    {'word': '六月', 'category': '数字时间', 'description': '先做月手势，然后做数字6', 'video_path': 'videos/signs/number_time/liu_yue.mp4'},
    {'word': '七月', 'category': '数字时间', 'description': '先做月手势，然后做数字7', 'video_path': 'videos/signs/number_time/qi_yue.mp4'},
    {'word': '八月', 'category': '数字时间', 'description': '先做月手势，然后做数字8', 'video_path': 'videos/signs/number_time/ba_yue.mp4'},
    {'word': '九月', 'category': '数字时间', 'description': '先做月手势，然后做数字9', 'video_path': 'videos/signs/number_time/jiu_yue.mp4'},
    {'word': '十月', 'category': '数字时间', 'description': '先做月手势，然后做数字10', 'video_path': 'videos/signs/number_time/shi_yue.mp4'},
    {'word': '十一月', 'category': '数字时间', 'description': '先做月手势，然后做数字11', 'video_path': 'videos/signs/number_time/shi_yi_yue.mp4'},
    {'word': '十二月', 'category': '数字时间', 'description': '先做月手势，然后做数字12', 'video_path': 'videos/signs/number_time/shi_er_yue.mp4'},
    {'word': '年', 'category': '数字时间', 'description': '右手握拳绕圈，表示地球绕太阳', 'video_path': 'videos/signs/number_time/nian.mp4'},
    {'word': '今年', 'category': '数字时间', 'description': '先做年手势，然后指自己', 'video_path': 'videos/signs/number_time/jin_nian.mp4'},
    {'word': '明年', 'category': '数字时间', 'description': '先做年手势，然后向前指', 'video_path': 'videos/signs/number_time/ming_nian.mp4'},
    {'word': '去年', 'category': '数字时间', 'description': '先做年手势，然后向后指', 'video_path': 'videos/signs/number_time/qu_nian.mp4'},
    {'word': '小时', 'category': '数字时间', 'description': '右手食指指左手腕', 'video_path': 'videos/signs/number_time/xiao_shi.mp4'},
    {'word': '分钟', 'category': '数字时间', 'description': '右手食指在左手腕上画小圈', 'video_path': 'videos/signs/number_time/fen_zhong.mp4'},
    {'word': '秒', 'category': '数字时间', 'description': '右手食指快速点左手腕', 'video_path': 'videos/signs/number_time/miao.mp4'},
    {'word': '早上', 'category': '数字时间', 'description': '右手从下向上画弧线', 'video_path': 'videos/signs/number_time/zao_shang.mp4'},
    {'word': '中午', 'category': '数字时间', 'description': '右手在头顶画圈', 'video_path': 'videos/signs/number_time/zhong_wu.mp4'},
    {'word': '下午', 'category': '数字时间', 'description': '右手从上向下画弧线', 'video_path': 'videos/signs/number_time/xia_wu.mp4'},
    {'word': '晚上', 'category': '数字时间', 'description': '右手在面前画月亮', 'video_path': 'videos/signs/number_time/wan_shang.mp4'},
    {'word': '凌晨', 'category': '数字时间', 'description': '右手在脸旁做睡觉状', 'video_path': 'videos/signs/number_time/ling_chen.mp4'},
    {'word': '春天', 'category': '数字时间', 'description': '双手向上做发芽状', 'video_path': 'videos/signs/number_time/chun_tian.mp4'},
    {'word': '夏天', 'category': '数字时间', 'description': '右手在额头擦汗', 'video_path': 'videos/signs/number_time/xia_tian.mp4'},
    {'word': '秋天', 'category': '数字时间', 'description': '双手做落叶状', 'video_path': 'videos/signs/number_time/qiu_tian.mp4'},
    {'word': '冬天', 'category': '数字时间', 'description': '双手抱肩做发抖状', 'video_path': 'videos/signs/number_time/dong_tian.mp4'},
    {'word': '过去', 'category': '数字时间', 'description': '右手向后指', 'video_path': 'videos/signs/number_time/guo_qu.mp4'},
    {'word': '未来', 'category': '数字时间', 'description': '右手向前指', 'video_path': 'videos/signs/number_time/wei_lai.mp4'},
    {'word': '永远', 'category': '数字时间', 'description': '右手食指画大圈', 'video_path': 'videos/signs/number_time/yong_yuan.mp4'},
  ];

  // 地点方向 (20个)
  static List<Map<String, String>> locationWords = [
    {'word': '家', 'category': '地点方向', 'description': '双手搭成屋顶形状', 'video_path': 'videos/signs/location/jia.mp4'},
    {'word': '学校', 'category': '地点方向', 'description': '右手在左手掌上写字', 'video_path': 'videos/signs/location/xue_xiao.mp4'},
    {'word': '医院', 'category': '地点方向', 'description': '右手在左手腕上做打针状', 'video_path': 'videos/signs/location/yi_yuan.mp4'},
    {'word': '超市', 'category': '地点方向', 'description': '双手做推购物车状', 'video_path': 'videos/signs/location/chao_shi.mp4'},
    {'word': '商场', 'category': '地点方向', 'description': '双手比划大房子形状', 'video_path': 'videos/signs/location/shang_chang.mp4'},
    {'word': '银行', 'category': '地点方向', 'description': '右手做数钱状', 'video_path': 'videos/signs/location/yin_hang.mp4'},
    {'word': '邮局', 'category': '地点方向', 'description': '右手做贴邮票状', 'video_path': 'videos/signs/location/you_ju.mp4'},
    {'word': '公园', 'category': '地点方向', 'description': '双手做树形状', 'video_path': 'videos/signs/location/gong_yuan.mp4'},
    {'word': '电影院', 'category': '地点方向', 'description': '双手比划屏幕形状', 'video_path': 'videos/signs/location/dian_ying_yuan.mp4'},
    {'word': '餐厅', 'category': '地点方向', 'description': '右手做吃饭状', 'video_path': 'videos/signs/location/can_ting.mp4'},
    {'word': '图书馆', 'category': '地点方向', 'description': '双手做翻书状', 'video_path': 'videos/signs/location/tu_shu_guan.mp4'},
    {'word': '车站', 'category': '地点方向', 'description': '右手做火车开动状', 'video_path': 'videos/signs/location/che_zhan.mp4'},
    {'word': '机场', 'category': '地点方向', 'description': '右手做飞机飞行状', 'video_path': 'videos/signs/location/ji_chang.mp4'},
    {'word': '酒店', 'category': '地点方向', 'description': '双手做开门状', 'video_path': 'videos/signs/location/jiu_dian.mp4'},
    {'word': '办公室', 'category': '地点方向', 'description': '右手做写字状', 'video_path': 'videos/signs/location/bangong_shi.mp4'},
    {'word': '东', 'category': '地点方向', 'description': '右手向右指（日出方向）', 'video_path': 'videos/signs/location/dong.mp4'},
    {'word': '南', 'category': '地点方向', 'description': '右手向下指', 'video_path': 'videos/signs/location/nan.mp4'},
    {'word': '西', 'category': '地点方向', 'description': '右手向左指', 'video_path': 'videos/signs/location/xi.mp4'},
    {'word': '北', 'category': '地点方向', 'description': '右手向上指', 'video_path': 'videos/signs/location/bei.mp4'},
    {'word': '方向', 'category': '地点方向', 'description': '右手食指指向前方', 'video_path': 'videos/signs/location/fang_xiang.mp4'},
  ];

  // 人物称谓 (30个)
  static List<Map<String, String>> peopleWords = [
    {'word': '爸爸', 'category': '人物称谓', 'description': '右手拇指抵住额头', 'video_path': 'videos/signs/people/ba_ba.mp4'},
    {'word': '妈妈', 'category': '人物称谓', 'description': '右手拇指抵住下巴', 'video_path': 'videos/signs/people/ma_ma.mp4'},
    {'word': '爷爷', 'category': '人物称谓', 'description': '右手做捋胡子状', 'video_path': 'videos/signs/people/ye_ye.mp4'},
    {'word': '奶奶', 'category': '人物称谓', 'description': '右手在鬓角处做白发状', 'video_path': 'videos/signs/people/nai_nai.mp4'},
    {'word': '哥哥', 'category': '人物称谓', 'description': '右手食指指太阳穴，然后向前', 'video_path': 'videos/signs/people/ge_ge.mp4'},
    {'word': '姐姐', 'category': '人物称谓', 'description': '右手食指在脸颊划一下', 'video_path': 'videos/signs/people/jie_jie.mp4'},
    {'word': '弟弟', 'category': '人物称谓', 'description': '右手小指竖起', 'video_path': 'videos/signs/people/di_di.mp4'},
    {'word': '妹妹', 'category': '人物称谓', 'description': '右手小指在脸颊划一下', 'video_path': 'videos/signs/people/mei_mei.mp4'},
    {'word': '儿子', 'category': '人物称谓', 'description': '右手做抱婴儿状', 'video_path': 'videos/signs/people/er_zi.mp4'},
    {'word': '女儿', 'category': '人物称谓', 'description': '右手做梳辫子状', 'video_path': 'videos/signs/people/nv_er.mp4'},
    {'word': '丈夫', 'category': '人物称谓', 'description': '右手拍左肩', 'video_path': 'videos/signs/people/zhang_fu.mp4'},
    {'word': '妻子', 'category': '人物称谓', 'description': '右手做戴戒指状', 'video_path': 'videos/signs/people/qi_zi.mp4'},
    {'word': '朋友', 'category': '人物称谓', 'description': '双手食指勾在一起', 'video_path': 'videos/signs/people/peng_you.mp4'},
    {'word': '同学', 'category': '人物称谓', 'description': '双手做翻书状，然后指向对方', 'video_path': 'videos/signs/people/tong_xue.mp4'},
    {'word': '同事', 'category': '人物称谓', 'description': '右手做写字状，然后指向对方', 'video_path': 'videos/signs/people/tong_shi.mp4'},
    {'word': '老师', 'category': '人物称谓', 'description': '右手在额前敬礼', 'video_path': 'videos/signs/people/lao_shi.mp4'},
    {'word': '学生', 'category': '人物称谓', 'description': '右手在胸前做写字状', 'video_path': 'videos/signs/people/xue_sheng.mp4'},
    {'word': '医生', 'category': '人物称谓', 'description': '右手在左手腕做听诊状', 'video_path': 'videos/signs/people/yi_sheng.mp4'},
    {'word': '护士', 'category': '人物称谓', 'description': '右手做打针状', 'video_path': 'videos/signs/people/hu_shi.mp4'},
    {'word': '警察', 'category': '人物称谓', 'description': '右手在额头敬礼', 'video_path': 'videos/signs/people/jing_cha.mp4'},
    {'word': '司机', 'category': '人物称谓', 'description': '双手做握方向盘状', 'video_path': 'videos/signs/people/si_ji.mp4'},
    {'word': '老板', 'category': '人物称谓', 'description': '右手拍口袋，表示有钱', 'video_path': 'videos/signs/people/lao_ban.mp4'},
    {'word': '员工', 'category': '人物称谓', 'description': '右手做写字状', 'video_path': 'videos/signs/people/yuan_gong.mp4'},
    {'word': '客人', 'category': '人物称谓', 'description': '右手做邀请状', 'video_path': 'videos/signs/people/ke_ren.mp4'},
    {'word': '主人', 'category': '人物称谓', 'description': '右手拍胸口', 'video_path': 'videos/signs/people/zhu_ren.mp4'},
    {'word': '邻居', 'category': '人物称谓', 'description': '右手向左指，然后向右指', 'video_path': 'videos/signs/people/lin_ju.mp4'},
    {'word': '亲戚', 'category': '人物称谓', 'description': '双手食指勾在一起转圈', 'video_path': 'videos/signs/people/qin_qi.mp4'},
    {'word': '陌生人', 'category': '人物称谓', 'description': '右手在眼前做遮挡状', 'video_path': 'videos/signs/people/mo_sheng_ren.mp4'},
    {'word': '中国人', 'category': '人物称谓', 'description': '右手食指在胸口画"中"字', 'video_path': 'videos/signs/people/zhong_guo_ren.mp4'},
    {'word': '外国人', 'category': '人物称谓', 'description': '右手在脸前做高鼻梁状', 'video_path': 'videos/signs/people/wai_guo_ren.mp4'},
  ];

  // 动作行为 (20个)
  static List<Map<String, String>> actionWords = [
    {'word': '走', 'category': '动作行为', 'description': '双手食指和中指交替向前', 'video_path': 'videos/signs/action/zou.mp4'},
    {'word': '跑', 'category': '动作行为', 'description': '双手握拳快速摆动', 'video_path': 'videos/signs/action/pao.mp4'},
    {'word': '跳', 'category': '动作行为', 'description': '右手向上弹起', 'video_path': 'videos/signs/action/tiao.mp4'},
    {'word': '坐', 'category': '动作行为', 'description': '右手向下按，表示坐下', 'video_path': 'videos/signs/action/zuo.mp4'},
    {'word': '站', 'category': '动作行为', 'description': '右手向上举，表示站起', 'video_path': 'videos/signs/action/zhan.mp4'},
    {'word': '吃', 'category': '动作行为', 'description': '右手做拿食物到嘴边的动作', 'video_path': 'videos/signs/action/chi.mp4'},
    {'word': '喝', 'category': '动作行为', 'description': '右手做拿杯子喝水的动作', 'video_path': 'videos/signs/action/he.mp4'},
    {'word': '睡', 'category': '动作行为', 'description': '双手合十放在脸颊旁', 'video_path': 'videos/signs/action/shui.mp4'},
    {'word': '醒', 'category': '动作行为', 'description': '右手从眼前打开', 'video_path': 'videos/signs/action/xing.mp4'},
    {'word': '哭', 'category': '动作行为', 'description': '双手从眼睛向下划', 'video_path': 'videos/signs/action/ku.mp4'},
    {'word': '笑', 'category': '动作行为', 'description': '双手食指从嘴角向上划', 'video_path': 'videos/signs/action/xiao.mp4'},
    {'word': '唱', 'category': '动作行为', 'description': '右手在嘴前做唱歌状', 'video_path': 'videos/signs/action/chang.mp4'},
    {'word': '跳', 'category': '动作行为', 'description': '双手做跳舞状', 'video_path': 'videos/signs/action/tiao_wu.mp4'},
    {'word': '游', 'category': '动作行为', 'description': '双手做游泳状', 'video_path': 'videos/signs/action/you.mp4'},
    {'word': '飞', 'category': '动作行为', 'description': '双手做翅膀扇动状', 'video_path': 'videos/signs/action/fei.mp4'},
    {'word': '开', 'category': '动作行为', 'description': '双手做开门状', 'video_path': 'videos/signs/action/kai.mp4'},
    {'word': '关', 'category': '动作行为', 'description': '双手做关门状', 'video_path': 'videos/signs/action/guan.mp4'},
    {'word': '洗', 'category': '动作行为', 'description': '双手做搓洗状', 'video_path': 'videos/signs/action/xi.mp4'},
    {'word': '擦', 'category': '动作行为', 'description': '右手做擦拭动作', 'video_path': 'videos/signs/action/ca.mp4'},
    {'word': '抱', 'category': '动作行为', 'description': '双手做怀抱状', 'video_path': 'videos/signs/action/bao.mp4'},
  ];

  // 学习教育 (20个)
  static List<Map<String, String>> educationWords = [
    {'word': '学习', 'category': '学习教育', 'description': '双手在眼前做翻书状', 'video_path': 'videos/signs/education/xue_xi.mp4'},
    {'word': '读书', 'category': '学习教育', 'description': '右手在嘴前做读书状', 'video_path': 'videos/signs/education/du_shu.mp4'},
    {'word': '写字', 'category': '学习教育', 'description': '右手做写字状', 'video_path': 'videos/signs/education/xie_zi.mp4'},
    {'word': '画画', 'category': '学习教育', 'description': '右手做画画状', 'video_path': 'videos/signs/education/hua_hua.mp4'},
    {'word': '计算', 'category': '学习教育', 'description': '右手做打算盘状', 'video_path': 'videos/signs/education/ji_suan.mp4'},
    {'word': '思考', 'category': '学习教育', 'description': '右手食指指太阳穴', 'video_path': 'videos/signs/education/si_kao.mp4'},
    {'word': '记忆', 'category': '学习教育', 'description': '右手食指在太阳穴转圈', 'video_path': 'videos/signs/education/ji_yi.mp4'},
    {'word': '忘记', 'category': '学习教育', 'description': '右手在额头前摆动', 'video_path': 'videos/signs/education/wang_ji.mp4'},
    {'word': '考试', 'category': '学习教育', 'description': '右手做写字状，然后擦汗', 'video_path': 'videos/signs/education/kao_shi.mp4'},
    {'word': '成绩', 'category': '学习教育', 'description': '右手做写分数状', 'video_path': 'videos/signs/education/cheng_ji.mp4'},
    {'word': '及格', 'category': '学习教育', 'description': '右手做打勾状', 'video_path': 'videos/signs/education/ji_ge.mp4'},
    {'word': '优秀', 'category': '学习教育', 'description': '右手拇指竖起', 'video_path': 'videos/signs/education/you_xiu.mp4'},
    {'word': '失败', 'category': '学习教育', 'description': '双手向下摊开', 'video_path': 'videos/signs/education/shi_bai.mp4'},
    {'word': '进步', 'category': '学习教育', 'description': '右手向上移动', 'video_path': 'videos/signs/education/jin_bu.mp4'},
    {'word': '退步', 'category': '学习教育', 'description': '右手向下移动', 'video_path': 'videos/signs/education/tui_bu.mp4'},
    {'word': '知识', 'category': '学习教育', 'description': '右手从额头向前拿出', 'video_path': 'videos/signs/education/zhi_shi.mp4'},
    {'word': '文化', 'category': '学习教育', 'description': '双手做翻书状', 'video_path': 'videos/signs/education/wen_hua.mp4'},
    {'word': '科学', 'category': '学习教育', 'description': '右手做试管状', 'video_path': 'videos/signs/education/ke_xue.mp4'},
    {'word': '技术', 'category': '学习教育', 'description': '双手做操作机器状', 'video_path': 'videos/signs/education/ji_shu.mp4'},
    {'word': '语言', 'category': '学习教育', 'description': '右手从嘴边向前', 'video_path': 'videos/signs/education/yu_yan.mp4'},
  ];

  // 医疗健康 (20个)
  static List<Map<String, String>> healthWords = [
    {'word': '健康', 'category': '医疗健康', 'description': '右手拍胸口，表示身体好', 'video_path': 'videos/signs/health/jian_kang.mp4'},
    {'word': '生病', 'category': '医疗健康', 'description': '右手捂额头，做难受状', 'video_path': 'videos/signs/health/sheng_bing.mp4'},
    {'word': '头疼', 'category': '医疗健康', 'description': '右手捂额头', 'video_path': 'videos/signs/health/tou_teng.mp4'},
    {'word': '发烧', 'category': '医疗健康', 'description': '右手在额头试温度', 'video_path': 'videos/signs/health/fa_shao.mp4'},
    {'word': '咳嗽', 'category': '医疗健康', 'description': '右手捂嘴咳嗽', 'video_path': 'videos/signs/health/ke_sou.mp4'},
    {'word': '感冒', 'category': '医疗健康', 'description': '右手在鼻子前扇风', 'video_path': 'videos/signs/health/gan_mao.mp4'},
    {'word': '吃药', 'category': '医疗健康', 'description': '右手做拿药到嘴边的动作', 'video_path': 'videos/signs/health/chi_yao.mp4'},
    {'word': '打针', 'category': '医疗健康', 'description': '右手做打针状', 'video_path': 'videos/signs/health/da_zhen.mp4'},
    {'word': '手术', 'category': '医疗健康', 'description': '双手做开刀状', 'video_path': 'videos/signs/health/shou_shu.mp4'},
    {'word': '检查', 'category': '医疗健康', 'description': '右手在身体前扫描', 'video_path': 'videos/signs/health/jian_cha.mp4'},
    {'word': '治疗', 'category': '医疗健康', 'description': '双手做包扎状', 'video_path': 'videos/signs/health/zhi_liao.mp4'},
    {'word': '康复', 'category': '医疗健康', 'description': '双手向上举起', 'video_path': 'videos/signs/health/kang_fu.mp4'},
    {'word': '医生', 'category': '医疗健康', 'description': '右手在胸口画"十"字', 'video_path': 'videos/signs/health/yi_sheng2.mp4'},
    {'word': '护士', 'category': '医疗健康', 'description': '右手做量血压状', 'video_path': 'videos/signs/health/hu_shi2.mp4'},
    {'word': '医院', 'category': '医疗健康', 'description': '双手搭成"十"字', 'video_path': 'videos/signs/health/yi_yuan2.mp4'},
    {'word': '药', 'category': '医疗健康', 'description': '右手做拿药丸状', 'video_path': 'videos/signs/health/yao.mp4'},
    {'word': '疼', 'category': '医疗健康', 'description': '右手捂疼痛部位', 'video_path': 'videos/signs/health/teng.mp4'},
    {'word': '痒', 'category': '医疗健康', 'description': '右手做挠痒状', 'video_path': 'videos/signs/health/yang.mp4'},
    {'word': '流血', 'category': '医疗健康', 'description': '右手做流血状', 'video_path': 'videos/signs/health/liu_xue.mp4'},
    {'word': '急救', 'category': '医疗健康', 'description': '双手快速做心脏按压', 'video_path': 'videos/signs/health/ji_jiu.mp4'},
  ];

  // 餐饮饮食 (20个)
  static List<Map<String, String>> foodWords = [
    {'word': '吃', 'category': '餐饮饮食', 'description': '右手做拿食物到嘴边的动作', 'video_path': 'videos/signs/food/chi.mp4'},
    {'word': '喝', 'category': '餐饮饮食', 'description': '右手做拿杯子喝水的动作', 'video_path': 'videos/signs/food/he.mp4'},
    {'word': '饭', 'category': '餐饮饮食', 'description': '右手做扒饭状', 'video_path': 'videos/signs/food/fan.mp4'},
    {'word': '菜', 'category': '餐饮饮食', 'description': '右手做夹菜状', 'video_path': 'videos/signs/food/cai.mp4'},
    {'word': '肉', 'category': '餐饮饮食', 'description': '右手做撕肉状', 'video_path': 'videos/signs/food/rou.mp4'},
    {'word': '鱼', 'category': '餐饮饮食', 'description': '双手做鱼游动状', 'video_path': 'videos/signs/food/yu.mp4'},
    {'word': '水果', 'category': '餐饮饮食', 'description': '右手做拿苹果状', 'video_path': 'videos/signs/food/shui_guo.mp4'},
    {'word': '水', 'category': '餐饮饮食', 'description': '右手做喝水状', 'video_path': 'videos/signs/food/shui.mp4'},
    {'word': '茶', 'category': '餐饮饮食', 'description': '右手做端茶杯状', 'video_path': 'videos/signs/food/cha.mp4'},
    {'word': '咖啡', 'category': '餐饮饮食', 'description': '右手做搅拌咖啡状', 'video_path': 'videos/signs/food/ka_fei.mp4'},
    {'word': '酒', 'category': '餐饮饮食', 'description': '右手做举杯状', 'video_path': 'videos/signs/food/jiu.mp4'},
    {'word': '牛奶', 'category': '餐饮饮食', 'description': '右手做挤牛奶状', 'video_path': 'videos/signs/food/niu_nai.mp4'},
    {'word': '面包', 'category': '餐饮饮食', 'description': '双手做掰面包状', 'video_path': 'videos/signs/food/mian_bao.mp4'},
    {'word': '鸡蛋', 'category': '餐饮饮食', 'description': '双手做鸡蛋形状', 'video_path': 'videos/signs/food/ji_dan.mp4'},
    {'word': '面条', 'category': '餐饮饮食', 'description': '右手做挑面条状', 'video_path': 'videos/signs/food/mian_tiao.mp4'},
    {'word': '汤', 'category': '餐饮饮食', 'description': '右手做舀汤状', 'video_path': 'videos/signs/food/tang.mp4'},
    {'word': '饿', 'category': '餐饮饮食', 'description': '右手捂肚子', 'video_path': 'videos/signs/food/e.mp4'},
    {'word': '饱', 'category': '餐饮饮食', 'description': '右手在肚子前画圈', 'video_path': 'videos/signs/food/bao.mp4'},
    {'word': '渴', 'category': '餐饮饮食', 'description': '右手做喝水状', 'video_path': 'videos/signs/food/ke.mp4'},
    {'word': '餐厅', 'category': '餐饮饮食', 'description': '右手做吃饭状，然后画圈', 'video_path': 'videos/signs/food/can_ting2.mp4'},
  ];

  // 出行交通 (20个)
  static List<Map<String, String>> transportWords = [
    {'word': '车', 'category': '出行交通', 'description': '双手做握方向盘状', 'video_path': 'videos/signs/transport/che.mp4'},
    {'word': '汽车', 'category': '出行交通', 'description': '双手做开车状', 'video_path': 'videos/signs/transport/qi_che.mp4'},
    {'word': '公交车', 'category': '出行交通', 'description': '右手做按铃状', 'video_path': 'videos/signs/transport/gong_jiao_che.mp4'},
    {'word': '地铁', 'category': '出行交通', 'description': '右手做地铁穿行状', 'video_path': 'videos/signs/transport/di_tie.mp4'},
    {'word': '火车', 'category': '出行交通', 'description': '双手做火车轮转动状', 'video_path': 'videos/signs/transport/huo_che.mp4'},
    {'word': '飞机', 'category': '出行交通', 'description': '右手做飞机飞行状', 'video_path': 'videos/signs/transport/fei_ji.mp4'},
    {'word': '船', 'category': '出行交通', 'description': '双手做划船状', 'video_path': 'videos/signs/transport/chuan.mp4'},
    {'word': '自行车', 'category': '出行交通', 'description': '双手做骑自行车状', 'video_path': 'videos/signs/transport/zi_xing_che.mp4'},
    {'word': '摩托车', 'category': '出行交通', 'description': '双手做骑摩托车状', 'video_path': 'videos/signs/transport/mo_tuo_che.mp4'},
    {'word': '走路', 'category': '出行交通', 'description': '双手食指和中指交替向前', 'video_path': 'videos/signs/transport/zou_lu.mp4'},
    {'word': '开车', 'category': '出行交通', 'description': '双手做握方向盘状', 'video_path': 'videos/signs/transport/kai_che.mp4'},
    {'word': '停车', 'category': '出行交通', 'description': '右手做停车手势', 'video_path': 'videos/signs/transport/ting_che.mp4'},
    {'word': '车站', 'category': '出行交通', 'description': '右手做火车进站状', 'video_path': 'videos/signs/transport/che_zhan2.mp4'},
    {'word': '机场', 'category': '出行交通', 'description': '右手做飞机起飞状', 'video_path': 'videos/signs/transport/ji_chang2.mp4'},
    {'word': '码头', 'category': '出行交通', 'description': '双手做波浪状', 'video_path': 'videos/signs/transport/ma_tou.mp4'},
    {'word': '红灯', 'category': '出行交通', 'description': '右手做停止状', 'video_path': 'videos/signs/transport/hong_deng.mp4'},
    {'word': '绿灯', 'category': '出行交通', 'description': '右手向前指', 'video_path': 'videos/signs/transport/lv_deng.mp4'},
    {'word': '黄灯', 'category': '出行交通', 'description': '右手做等待状', 'video_path': 'videos/signs/transport/huang_deng.mp4'},
    {'word': '安全带', 'category': '出行交通', 'description': '右手做系安全带状', 'video_path': 'videos/signs/transport/an_quan_dai.mp4'},
    {'word': '汽油', 'category': '出行交通', 'description': '右手做加油状', 'video_path': 'videos/signs/transport/qi_you.mp4'},
  ];

  // 娱乐运动 (15个)
  static List<Map<String, String>> entertainmentWords = [
    {'word': '玩', 'category': '娱乐运动', 'description': '双手做玩耍状', 'video_path': 'videos/signs/entertainment/wan.mp4'},
    {'word': '游戏', 'category': '娱乐运动', 'description': '双手做操纵游戏机状', 'video_path': 'videos/signs/entertainment/you_xi.mp4'},
    {'word': '电影', 'category': '娱乐运动', 'description': '双手比划屏幕形状', 'video_path': 'videos/signs/entertainment/dian_ying.mp4'},
    {'word': '电视', 'category': '娱乐运动', 'description': '右手做按遥控器状', 'video_path': 'videos/signs/entertainment/dian_shi.mp4'},
    {'word': '音乐', 'category': '娱乐运动', 'description': '双手做弹钢琴状', 'video_path': 'videos/signs/entertainment/yin_yue.mp4'},
    {'word': '唱歌', 'category': '娱乐运动', 'description': '右手在嘴前做唱歌状', 'video_path': 'videos/signs/entertainment/chang_ge.mp4'},
    {'word': '跳舞', 'category': '娱乐运动', 'description': '双手做跳舞状', 'video_path': 'videos/signs/entertainment/tiao_wu.mp4'},
    {'word': '运动', 'category': '娱乐运动', 'description': '双手做跑步状', 'video_path': 'videos/signs/entertainment/yun_dong.mp4'},
    {'word': '篮球', 'category': '娱乐运动', 'description': '双手做投篮状', 'video_path': 'videos/signs/entertainment/lan_qiu.mp4'},
    {'word': '足球', 'category': '娱乐运动', 'description': '右脚做踢球状', 'video_path': 'videos/signs/entertainment/zu_qiu.mp4'},
    {'word': '游泳', 'category': '娱乐运动', 'description': '双手做游泳状', 'video_path': 'videos/signs/entertainment/you_yong.mp4'},
    {'word': '跑步', 'category': '娱乐运动', 'description': '双手快速摆动', 'video_path': 'videos/signs/entertainment/pao_bu.mp4'},
    {'word': '爬山', 'category': '娱乐运动', 'description': '双手做攀爬状', 'video_path': 'videos/signs/entertainment/pa_shan.mp4'},
    {'word': '钓鱼', 'category': '娱乐运动', 'description': '双手做钓鱼状', 'video_path': 'videos/signs/entertainment/diao_yu.mp4'},
    {'word': '旅游', 'category': '娱乐运动', 'description': '右手向前指，然后画圈', 'video_path': 'videos/signs/entertainment/lv_you.mp4'},
  ];

  // 生活服务 (20个)
  static List<Map<String, String>> serviceWords = [
    {'word': '银行', 'category': '生活服务', 'description': '右手做数钱状', 'video_path': 'videos/signs/service/yin_hang.mp4'},
    {'word': '邮局', 'category': '生活服务', 'description': '右手做贴邮票状', 'video_path': 'videos/signs/service/you_ju.mp4'},
    {'word': '超市', 'category': '生活服务', 'description': '双手做推购物车状', 'video_path': 'videos/signs/service/chao_shi.mp4'},
    {'word': '理发', 'category': '生活服务', 'description': '右手做剪头发状', 'video_path': 'videos/signs/service/li_fa.mp4'},
    {'word': '洗衣', 'category': '生活服务', 'description': '双手做搓洗衣服状', 'video_path': 'videos/signs/service/xi_yi.mp4'},
    {'word': '修理', 'category': '生活服务', 'description': '双手做修理工具状', 'video_path': 'videos/signs/service/xiu_li.mp4'},
    {'word': '清洁', 'category': '生活服务', 'description': '右手做扫地状', 'video_path': 'videos/signs/service/qing_jie.mp4'},
    {'word': '保安', 'category': '生活服务', 'description': '右手在额头敬礼', 'video_path': 'videos/signs/service/bao_an.mp4'},
    {'word': '服务员', 'category': '生活服务', 'description': '右手做端盘子状', 'video_path': 'videos/signs/service/fu_wu_yuan.mp4'},
    {'word': '快递', 'category': '生活服务', 'description': '右手做递包裹状', 'video_path': 'videos/signs/service/kuai_di.mp4'},
    {'word': '外卖', 'category': '生活服务', 'description': '右手做送餐状', 'video_path': 'videos/signs/service/wai_mai.mp4'},
    {'word': '租房', 'category': '生活服务', 'description': '双手做签合同状', 'video_path': 'videos/signs/service/zu_fang.mp4'},
    {'word': '买房', 'category': '生活服务', 'description': '右手做数钱状，然后画房子', 'video_path': 'videos/signs/service/mai_fang.mp4'},
    {'word': '装修', 'category': '生活服务', 'description': '双手做刷墙状', 'video_path': 'videos/signs/service/zhuang_xiu.mp4'},
    {'word': '搬家', 'category': '生活服务', 'description': '双手做抬箱子状', 'video_path': 'videos/signs/service/ban_jia.mp4'},
    {'word': '保险', 'category': '生活服务', 'description': '右手做签保单状', 'video_path': 'videos/signs/service/bao_xian.mp4'},
    {'word': '法律', 'category': '生活服务', 'description': '右手做敲法槌状', 'video_path': 'videos/signs/service/fa_lv.mp4'},
    {'word': '警察', 'category': '生活服务', 'description': '右手在额头敬礼', 'video_path': 'videos/signs/service/jing_cha.mp4'},
    {'word': '消防', 'category': '生活服务', 'description': '右手做喷水灭火状', 'video_path': 'videos/signs/service/xiao_fang.mp4'},
    {'word': '急救', 'category': '生活服务', 'description': '双手做心脏按压状', 'video_path': 'videos/signs/service/ji_jiu.mp4'},
  ];
}